### ISSUE TITLE
Redirecting Traffic Through MacBook Proxy to Bypass DPI on Smart TV

### ISSUE THREAD

**Issue by pavelkogen** [xvzc/SpoofDPI#116]
**Description:**

I am trying to bypass DPI blocking on YouTube by using the `spoof-dpi` utility on my MacBook. It works fine on the MacBook itself, but I also want to route traffic from my Samsung Smart TV through this proxy to watch YouTube in 4K without issues. However, the traffic from the TV does not seem to reach the `spoof-dpi` utility running on the MacBook.

**Home Network Setup:**

- **Router:** MikroTik hAP ac² (IP: 192.168.88.1)
  - RouterOS v6.49.15 (stable)
  - DNS-over-HTTPS setup using AdGuard DNS.
- **MacBook:** Running `spoof-dpi` (IP: 192.168.88.241)
  - macOS 14.5 (23F79)
- **Smart TV:** Samsung (IP: 192.168.88.236)

**`spoof-dpi` Settings:**

```sh
spoof-dpi -addr 0.0.0.0 -port 8080 -dns-addr 192.168.88.1 -debug
```

**Version:**

```sh
spoof-dpi v0.10.6
```

**Current Status:**

When I start `spoof-dpi` on my MacBook, it listens on port 8080, and debug logs show that it handles requests from the MacBook itself correctly. However, the traffic from the Smart TV does not reach the utility. I tried adding a NAT rule on my MikroTik router to redirect the TV's traffic to the MacBook, but it did not work.

**MikroTik NAT Rule:**

```sh
/ip firewall nat add chain=dstnat protocol=tcp dst-port=80,443 src-address=192.168.88.236 action=dst-nat to-addresses=192.168.88.241 to-ports=8080
```

Despite trying different configurations and even disabling all firewall rules, the traffic from the TV does not seem to be redirected correctly. 

**Question:**

How can I configure my network so that the Samsung Smart TV routes its traffic through the `spoof-dpi` proxy on my MacBook? Any guidance on setting this up or troubleshooting steps would be greatly appreciated.

Thank you!

**Comment by qmmp123** [comment]
+1

**Comment by dimnik70** [comment]
+1

**Comment by xvzc** [comment]
This os HTTP/HTTPS proxy(only handles layer 7 packets not all the tcp packets) so that you should somehow be able to set the HTTP/HTTPS proxy setting on your preferred device, otherwise you will have to hack the device.
