### ISSUE TITLE
FATAL - Error while changing proxy settings

### ISSUE THREAD

**Issue by onmahadev** [xvzc/SpoofDPI#118]
# Describe the bug
Hi! When i started i have error - FATAL - Error while changing proxy settings

# Client information

**OS**: osx Ventura 

**Version**: 13.5.2 (22G91)

# Additional context intel CPU

**Comment by xvzc** [comment]
I got the error a few times too. i think there's some issue related to OS permission. Try rebooting your computer.

**Comment by onmahadev** [comment]
All fine with new version! Thanx! All OK!

**Comment by valeriylo** [comment]
having the same issue on m-chip, sonoma 14.5

**Comment by vovs03** [comment]
# Error while changing proxy settings

> It's relevant for me. I has this problem too.

![Снимок экрана 2024-08-16 в 18 56 39](https://github.com/user-attachments/assets/041e12a4-3ca1-480c-b6d3-55e295429332)


## Client information

|Software | VERSION| 
|-|-|
| OSX Ventura| `13.6.7`|
| Golang | `go1.22.2 darwin/amd64` |
| spoof-dpi | `v0.10.8` |

## Settings in `~/.zshrc`

- `export PATH=$PATH:~/.spoof-dpi/bin`
- `alias google-chrome="open /Applications/Google\ Chrome.app"`

## My steps

- [x] 🖥 installed `spoof-dpi`
- [ x] set **settings** 👆
- [x] has Error, reboot, and has Error again.

> Anyone can help me, what me doing wrong?

**Comment by onmahadev** [comment]
I will add that I started from "sudo"! And it helped me, and I hope it will help you too

**Comment by vovs03** [comment]
@onmahadev 💚 Thank you very much! 💚 It's work for me now!

**Comment by onmahadev** [comment]
Haribol !!!
I am glad that I was able to help you!
Free youtube :)

**Comment by AndrusDL** [comment]
I had the same problem and didn’t even know what to do. I tried rebooting my PC and reinstalling spoofdpi. The problem was with my VPN, which was working automatically even though the GUI showed that it was off. You need to turn on VPN only after connecting to a spoofdpi.
