### ISSUE TITLE
AntiVirus Trojan Detection

### ISSUE THREAD

**Issue by hamaadraza** [xvzc/SpoofDPI#123]
# Describe the bug
So I installed this using go install and the .exe is being as Trojan by windows defender. It is really annoying because I restore the file and windows deletes it after few days again. 

Here's the virustotal scan: 
[Virustotal Scan](https://www.virustotal.com/gui/file/770c50bdd2cf06425df72cfb18acc4e155553fc9c8162e10c42ceb21d443efaa/detection)

![Screenshot](https://github.com/user-attachments/assets/fd9649a1-18ec-4f4e-aaa4-eb9c50237b03)

**Comment by slezkinis** [comment]
Add the file to exceptions
