### ISSUE TITLE
Doesn't work on Apple Silicon Chip

### ISSUE THREAD

**Issue by roloit** [xvzc/SpoofDPI#124]
Hi, I can't get any DPI-spoofing software to work on the apple m chip, on macOS. Is there a way to fix that?
And how to control blocklists? 
Thanks.

**Comment by abychko** [comment]
it works like a charm on my M2s. what did I do...

1 - set up system proxy to exclude your local network
2 - set up your browser to use system proxy, not manual, not off
3 - I build the binary with script https://pastebin.com/fHrdQBne, saved as ~/spoof-dpi

that's all

**Comment by roloit** [comment]
I followed your steps, and it still doesn't unblock anything. Can you please maybe make a step-by-step guide I could follow to completely replicate that? Maybe I missed something? Thanks.

**Comment by abychko** [comment]
> I followed your steps, and it still doesn't unblock anything. Can you please maybe make a step-by-step guide I could follow to completely replicate that? Maybe I missed something? Thanks.

just run the binary and take a look at system proxy settings: System Settings->Wifi (or Network->Ethernet)->Details->Proxies. it should look like on my screenshot
![Screenshot 2024-08-10 at 14 26 31](https://github.com/user-attachments/assets/49aa059f-d118-4c09-afd3-746e880ba083)

if everything is fine there - take a look at your browser settings. it should be set to use system proxy settings.
try to open some pages - unblocked and blocked. 
please note - sites may be blocked in different ways. if site is not DPIed but completely firewalled - this project will not help

**Comment by roloit** [comment]
So I set it up like that, and tried some other ways, but I didn't see any improvements... Does it unblock (blocked via DPI) websites for you? On other devices, in my case, other tools work, but somehow I can't make any DPI-spoofing tool to work on Mac...

**Comment by abychko** [comment]
> So I set it up like that, and tried some other ways, but I didn't see any improvements... Does it unblock (blocked via DPI) websites for you? On other devices, in my case, other tools work, but somehow I can't make any DPI-spoofing tool to work on Mac...

yes, it works for me on 2 Macs, for different ISPs. did you try to run it with --debug and check the log?

**Comment by roloit** [comment]
Nevermind, I don't think it works for me at all, I tried [https://github.com/bol-van/zapret](url) and it works just fine.

**Comment by wildburn** [comment]
> Nevermind, I don't think it works for me at all, I tried [https://github.com/bol-van/zapret](url) and it works just fine.

How did you build this zapret? I can't fully comprehend how it works. Did you just run install easy?
