### ISSUE TITLE
Problems with youtube preview

### ISSUE THREAD

**Issue by neu4h** [xvzc/SpoofDPI#128]
# Describe the bug

## Actual behavior

# How To Reproduce?

# Client information

**OS**:

**Version**:

# Additional context

**Comment by neu4h** [comment]
On YouTube, previews load poorly both on the main page and on the channel page if the videos are more than 2 years old. (Previews simply do not load there). The add-on, rutracker.org, which has been blocked for a long time, opened fine, but stopped. I am very grateful to you for the work you do, if possible, try to fix it. Thanks again.
I apologize for my English. Thank you.

**Comment by asimba** [comment]
Попробуйте  параметры (срабатывают у нескольких провайдеров): -no-banner -dns-addr=1.1.1.1 -enable-doh -addr=127.0.0.1 -port=8080 -window-size=2

**Comment by asimba** [comment]
Try:  -no-banner -dns-addr=1.1.1.1 -enable-doh -window-size=2
In browser: disable http3 (quic).

**Comment by neu4h** [comment]
Your advice helped.
/spoof-dpi no-banner -dns-addr 1.1.1.1 -port 8081 -enable-doh -window-size 2

Why, when running with the -port 8081 key, the application still runs on port 8080.

That is, this command works fine, all previews open well, but the port that opens is not 8081 as in the command, but 8080.
It's not critical, but I'd like to know the reason.

Thank you.

**Comment by neu4h** [comment]
Works with this command:

./spoof-dpi -no-banner -dns-addr=1.1.1.1 -port 8081 -enable-doh -window-size 2

Thanks.

**Comment by vgl266** [comment]
I got rid of the issue just by disabling quic (in Brave, it was on "Default" before, apparently that means enabled), all spoofdpi settings are vanilla including window size, but I have doh enabled via stubby on my router.
