### ISSUE TITLE
Request. Binary release for Windows.

### ISSUE THREAD

**Issue by ropucyka** [xvzc/SpoofDPI#134]
Actual.

**Comment by PoorMouse** [comment]
For Windows you can use GoodByeDPI.

**Comment by ropucyka** [comment]
> For Windows you can use GoodByeDPI.

I dont want to use WinDiwert shit for system wide, i want accurate and elegant proxy solution.

**Comment by xvzc** [comment]
Okay i will add the windows' binary release for the next release

**Comment by xvzc** [comment]
Done
