### ISSUE TITLE
[MacOS arm64] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by abychko** [xvzc/SpoofDPI#139]
# Describe the bug
spoof-dpi binary crashes after start on MacOS arm64

## Expected behavior
normal work

## Actual behavior
crash

# How To Reproduce?
rev: 4721bd60673f01c397b127cf234b08bca14c6832
built with  `GOOS=darwin GOARCH=arm64 go build '-ldflags=-w -s -X main.VERSION=v0.10.7' github.com/xvzc/SpoofDPI/cmd/spoof-dpi`

see crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100da1798]

goroutine 10 [running]:
github.com/xvzc/SpoofDPI/packet.(*HttpPacket).Raw(...)
	/Users/abychko/GitHub/SpoofDPI/packet/http.go:69
github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start.func1()
	/Users/abychko/GitHub/SpoofDPI/proxy/proxy.go:66 +0x518
created by github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start in goroutine 25
	/Users/abychko/GitHub/SpoofDPI/proxy/proxy.go:63 +0x310
```
# Client information

**OS**:
MacOS arm64 

**Version**:
Sonoma 14.5

# Additional context

**Comment by LiquidTheDangerous** [comment]
please, run with `-debug` and send logs

**Comment by LiquidTheDangerous** [comment]
will be ok, after merge #140
