### ISSUE TITLE
Release v0.5 error while access to listen port

### ISSUE THREAD

**Issue by zetcamp** [xvzc/SpoofDPI#14]
Just overwrite v0.5 over worked v0.4 on same test machine. While trying to access to listen port, I have an error in console output:

`panic: runtime error: index out of range [1] with length 1

goroutine 6 [running]:
github.com/xvzc/SpoofDPI/packet.parse({0xc000014130, 0xc000200000, 0x8e1da0})
        /SpoofDPI/packet/http.go:140 +0x210
github.com/xvzc/SpoofDPI/packet.NewHttpPacket({0xc000014130, 0x3, 0x8})
        /SpoofDPI/packet/http.go:57 +0x5a
github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start.func1()
        /SpoofDPI/proxy/proxy.go:50 +0x4e
created by github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start
        /SpoofDPI/proxy/proxy.go:43 +0x2bb`

Host machine is a LXC container with Ubuntu 20.04. Version v0.4 is working fine.

**Comment by xvzc** [comment]
i couldn't reproduce the issue but there was some problem handling http request.
i now the v0.5 banaries are updated.
try it again and tell me how it goes

**Comment by zetcamp** [comment]
> so try it again and tell me how it goes
Now there are no errors like above, thx. Everything is working.

Can I ask - is there any option (or add/modify an option) to force SpoofDPI use a native UDP DNS query to 53 port? I already have internal DNS-server for external DoH|DoT DNS querying.
For ex:
--dns=udp://x.x.x.x:53 - for direct UDP
--dns=tls://x.x.x.x:853 - DNS-over-TLS
--dns=https://x.x.x.x:443 - for DNS-over-HTTPS
etc.

Thank you.

**Comment by xvzc** [comment]
well, for the dns, i’m currently using a submodule https://github.com/babolivier/go-doh-client. i will take a look and if possible i will try to support it somehow. thx

**Comment by zetcamp** [comment]
Issue is fixed.
