### ISSUE TITLE
Using the "-pattern" option

### ISSUE THREAD

**Issue by k1ll1n** [xvzc/SpoofDPI#147]
Hi, could you show some example how to use the "-pattern" option?

**Comment by xvzc** [comment]
You can use any valid regex pattern `go run ./... --pattern '.*.youtube.com' --pattern 'google.com'`

**Comment by zimbabwe303** [comment]
Works for me to spoof only YouTube:
`-pattern "(youtube\.com)|(youtu\.be)|(googlevideo\.com)|(ytimg\.com)"`

**Comment by Ved-un** [comment]
Can we cut it down like this?    
```
-pattern "(?:youtube|googlevideo|rutracker)"
```
