### ISSUE TITLE
Failed to start on termux on android tablet

### ISSUE THREAD

**Issue by MaratZakirov** [xvzc/SpoofDPI#148]
# Describe the bug

Getting some internal error
# Client information

**OS**:

**Version**:

**Comand**

>>    export PATH=$PATH:~/.spoof-dpi/bin
~ $ с^C
~ $ rm -rf .spoof-dpi
~ $ curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s linux-arm64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17333  100 17333    0     0  78257      0 --:--:-- --:--:-- --:--:-- 78786
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2354k  100 2354k    0     0  1573k      0  0:00:01  0:00:01 --:--:-- 3588k
./spoof-dpi

Successfully installed SpoofDPI.
Please add the line below to your rcfile(.bashrc or .zshrc etc..)

>>    export PATH=$PATH:~/.spoof-dpi/bin
~ $ cd .spoof-dpi/
~/.spoof-dpi $ cd bin
~/.spoof-dpi/bin $ ls
spoof-dpi
~/.spoof-dpi/bin $ ./spoof-dpi
error: "/data/data/com.termux/files/home/.spoof-dpi/bin/spoof-dpi" has unexpected e_type: 2

# Additional context

**Comment by xvzc** [comment]
This project is not for android environment

**Comment by MaratZakirov** [comment]
I build it on android and it started in termux

**Comment by xvzc** [comment]
Yeah, but there's nothing weird even if it doesn't work on android because it hasn't been tested on android.
