### ISSUE TITLE
 in the version 0.10.8 you started using glibc 2.34

### ISSUE THREAD

**Issue by shurakr** [xvzc/SpoofDPI#152]
I don't have this version of the library on my asustor and only version 0.10.7 works
Can I ask you not to use new versions of glibc?

**Comment by LiquidTheDangerous** [comment]
@shurakr attach build output please

**Comment by LiquidTheDangerous** [comment]
@shurakr Dependency versions have not been updated since version 0.10.7, perhaps the language runtime requires this version

**Comment by LiquidTheDangerous** [comment]
@xvzc It might be worth creating a release without dependencies on the C runtime

**Comment by shurakr** [comment]
yes, that would be great

**Comment by LiquidTheDangerous** [comment]
#154 created PR
