### ISSUE TITLE
panic: runtime error: slice bounds out of range [:5] with capacity 0

### ISSUE THREAD

**Issue by Sergey-Bel** [xvzc/SpoofDPI#171]
# Describe the bug

# Client information

**OS**: macOS 14.6.1

**Version**: 0.10.8

**Command to run spoof-dpi**: spoof-dpi

# Additional context

panic: runtime error: slice bounds out of range [:5] with capacity 0

goroutine 270702 [running]:
github.com/xvzc/SpoofDPI/packet.ReadTLSMessage({0x1008f8858, 0x1400014c140})
	/home/runner/work/SpoofDPI/SpoofDPI/packet/https.go:47 +0x1e8
github.com/xvzc/SpoofDPI/proxy.(*Proxy).handleHttps(0x14000076280, 0x1400014c140, 0x1, 0x14000749e30, {0x1400002a407, 0xf})
	/home/runner/work/SpoofDPI/SpoofDPI/proxy/https.go:48 +0x3cc
github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start.func1()
	/home/runner/work/SpoofDPI/SpoofDPI/proxy/proxy.go:99 +0x440
created by github.com/xvzc/SpoofDPI/proxy.(*Proxy).Start in goroutine 49
	/home/runner/work/SpoofDPI/SpoofDPI/proxy/proxy.go:63 +0x310

**Comment by Sergey-Bel** [comment]
How to fix this problem?

**Comment by LiquidTheDangerous** [comment]
@Sergey-Bel can you attach logs please with '-debug' option. 

How to reproduce?

**Comment by Sergey-Bel** [comment]
@LiquidTheDangerous, 
[logs.txt](https://github.com/user-attachments/files/16677514/logs.txt)
 The problem appears after 30-40 minutes of watching YouTube.
CPU - M1

**Comment by LiquidTheDangerous** [comment]
@Sergey-Bel could you build and test spoof-dpi from this branch? #172

**Comment by Sergey-Bel** [comment]
@LiquidTheDangerous, I don't know how to do it.

**Comment by LiquidTheDangerous** [comment]
build it for you. [spoof-dpi-darwin-arm64.tar.gz](https://github.com/user-attachments/files/16677717/spoof-dpi-darwin-arm64.tar.gz)

**Comment by xvzc** [comment]
We should just make another release and see if any other issue raises

**Comment by Sergey-Bel** [comment]
@LiquidTheDangerous, 2 hours of watching youtube videos with no errors. Thank you!

**Comment by LiquidTheDangerous** [comment]
@Sergey-Bel ping after release please. Implementation a bit differ

**Comment by Sergey-Bel** [comment]
@LiquidTheDangerous, after restarting, the error is displayed: FATA[2024-08-20T19:59:45+03:00] [PROXY] Error creating listener: listen tcp4 127.0.0.1:8080: bind: address already in use.

**Comment by xvzc** [comment]
you should kill the previous process

**Comment by Sergey-Bel** [comment]
@xvzc, It's working again :)

**Comment by Sergey-Bel** [comment]
@LiquidTheDangerous 

> @Sergey-Bel ping after release please. Implementation a bit differ
[Uploading PING.txt…]()
