### ISSUE TITLE
Transparent proxy

### ISSUE THREAD

**Issue by romkazor** [xvzc/SpoofDPI#178]
Hello. How about add feature transparent proxy. Is it possible?

**Comment by xvzc** [comment]
What do you mean transparent? Sorry for my stupidity

**Comment by xvzc** [comment]
Basically if you give pattern argument, then the url that doesn't match the pattern will be sent transparently

**Comment by zimbabwe303** [comment]
Transparent proxy is a way of routing all traffic via a proxy. Usually done in iptables using the TPROXY extension for a PREROUTING rule in the NAT table. More on this here: https://www.kernel.org/doc/Documentation/networking/tproxy.txt

Not sure what it has to do with SpoofDPI. Automatic adding of the needed iptables rules may be?
