### ISSUE TITLE
Split tunneling for apps / app selection feature

### ISSUE THREAD

**Issue by noideastowork** [xvzc/SpoofDPI#179]
# Description
If possible, I'd like to propose adding an app selection feature (split tunneling) to SpoofDPI.

# Additional context
It would be great if you could choose in the application which apps should use SpoofDPI's proxy and which shouldn't as I don't want all my internet traffic to go through it.

**Comment by xvzc** [comment]
I think this is not technically possible

**Comment by noideastowork** [comment]
> I think this is not technically possible

I'm sorry to hear that. Thank you for your answer!

Just in case, I'll tell you what Adguard can do in this case (I apologize for mentioning it again). It seems to work as it uses Network Extension mode.

<img width="587" alt="image" src="https://github.com/user-attachments/assets/776766ad-74b8-4e38-ab2b-cc33ba32e476">
<img width="494" alt="image" src="https://github.com/user-attachments/assets/d92730c9-a37e-42b0-9820-0cd9e689bb83">
<img width="594" alt="image" src="https://github.com/user-attachments/assets/6d9e8bfc-b119-4980-8dc0-58b8705c743d">
