### ISSUE TITLE
Got cut off the internet (Steps to delete SpoofDPI)

### ISSUE THREAD

**Issue by sunriderrr** [xvzc/SpoofDPI#181]
# Describe the bug
After SpoofPDI was blocked in Russia, my Mac appeared to be totally cut off any Wi-Fi connection (except Whatsapp which was the olny app still working unstable ). I tried to delete SpoofDPI by prompting **rm -rf ~/.spoof-dpi** in Terminal but it didn't help at all. I still couldn't enter to the web.

Here's the only solution that helped me.
1. Open **Finder**
2. Open **Go** and enter the adress **/Library/Preferences/SystemConfiguration**. Press **Enter**
3. **Backup** the next files in the opened folder 
- preferences.plist
- NetworkInterfaces.plist
- com.apple.wifi.message-tracer.plist
- com.apple.network.eapolclient.configuration.plist
- com.apple.airport.preferences.plist
4. **Delete** these files 
5. **Reboot**
6. Done!

I didn't have 4th file but nevertheless it worked.

The solution is found here https://support.freevpnplanet.com/hc/ru/articles/6197347327004-%D0%9F%D1%80%D0%BE%D0%BF%D0%B0%D0%BB-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BD%D0%B0-macOS

# Client information

**OS**:
MacOS Monterey

**Version**:
 12.7.4

**Command to run spoof-dpi**:

# Additional context

**Comment by Ledorub** [comment]
I think, you could have gone to settings, searched for "proxy", and disabled both `Web Proxy (HTTP)` and `Secure Web Proxy (HTTPS)`, or used the shell commands from the source code.

**Comment by sunriderrr** [comment]
> I think, you could have gone to settings, searched for "proxy", and disabled both `Web Proxy (HTTP)` and `Secure Web Proxy (HTTPS)`, or used the shell commands from the source code.

I also forgot to add that while the cut off I still could connect to the internet with an turned on VPN.

**Comment by andreichirkov** [comment]
Thanks

**Comment by garaevruslan** [comment]
The same problems started due to spoof dpi just the other day. Your advice helped me fix the situation, thank you!
