### ISSUE TITLE
chore: create issue template

### ISSUE THREAD

**Issue by Ledorub** [xvzc/SpoofDPI#186]
Could you create an issue template that asks to provide the OS version and arch, as well as the SpoofDPI's version? On macOS the first thing can be done with:
```sh
sw_vers && echo "Architecture: \t\t$(uname -m)"
```
Not sure about a linux analogue. `uname -a`?

**Comment by xvzc** [comment]
Do you want this to prevent people from creating empty issue?

**Comment by Ledorub** [comment]
Not necessarily. Just to encourage people to provide more context.

**Comment by xvzc** [comment]
We can also force people to provide more information. rather than letting them know how to provide information. What do you think is better option?

**Comment by Ledorub** [comment]
Most of the issues are technical, and additional information would be beneficial. Especially in bug reports.

BTW, GitHub is working on some fancy [forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). They are still in beta, but if they don't require spending much time to set up, it may worth it.

**Comment by xvzc** [comment]
Yeah i've also seen that one, It seems like it is being used many projects with no problem?

**Comment by Ledorub** [comment]
Yes. The only drawback I know about is the inability to source dropdown element options from release tags.
