### ISSUE TITLE
Rename tags to follow a common spec

### ISSUE THREAD

**Issue by Ledorub** [xvzc/SpoofDPI#188]
### Description

Version tag names are inconsistent, which confuses some tools and they resolve 0.81 as being newer than 0.10.0. @xvzc, could you rename the tags to follow a single spec? I suggest to switch to [Semantic Versioning 2.0.0](https://semver.org/) and make all tags adhere to `Major.Minor.Patch` naming scheme.

So:
- `0.1` -> `0.1.0`
- `0.51` -> `0.5.1`
- `v0.10.0` -> `0.10.0` and so on.

**Comment by xvzc** [comment]
It will take some time

**Comment by xvzc** [comment]
All done. A lot of work ! ha.

**Comment by xvzc** [comment]
I think it's more common to have 'v' prefix in go modules according to [Proposal: Versioned Go Modules](https://go.googlesource.com/proposal/+/master/design/24301-versioned-go.md). Also removing 'v' prefix in tag led to a problem like #210.

**Comment by Ledorub** [comment]
It seems so. Unfortunately, I wasn't aware that Go is so picky about that. [Go guidelines](https://go.dev/doc/modules/version-numbers) indeed insist on using `v` prefix and call it semantic versioning, which it is not, according to the [SemVer spec](https://semver.org/#is-v123-a-semantic-version).

I don't like the idea that Go policies affect version control tag naming, but it is what it is. There was a lengthy discussion regarding this issue in Go issues, but the proposal to support both schemes was declined.

I apologize for bringing you extra work. I suggest you use something like [this script](https://gist.github.com/knu/111055?permalink_comment_id=5073739#gistcomment-5073739).

**Comment by xvzc** [comment]
It's okay it already all doen. but it turns out that the #210 is because of renaming the path of `main.go` to `spoofdpi`. However, i don't understand why go install latest command can not find `0.10.12`
