### ISSUE TITLE
Banner always "true" and never "false"

### ISSUE THREAD

**Issue by OlegKochkin** [xvzc/SpoofDPI#201]
### Version

0.10.11

### Operating System

linux-amd64

### How are you running SpoofDPI?

Run as service:
spoof-dpi -dns-addr 127.0.0.1 -addr 192.168.1.2 -port 4435

### Description

Default option = "true"
Args set only to "true"

**Comment by meloman27** [comment]
-banner=false

**Comment by Ledorub** [comment]
Have you tried running it with `-banner=false`?

**Comment by OlegKochkin** [comment]
> Have you tried running it with `-banner=false`?

This worked. Thanks.
