### ISSUE TITLE
versioning concerns

### ISSUE THREAD

**Issue by Ledorub** [xvzc/SpoofDPI#205]
### Description

A directory in the path to `main.go` has been renamed recently. That change breaks code that automates building/running process: packet manager formulas and user scripts.

I think that renaming was necessary for better consistency, but we really shouldn't introduce incompatible changes as **patch versions**. This will also lead to Homebrew [rejecting](https://docs.brew.sh/Versions) a new formula with updated build path.

I suggest that we use patch versions for fixes or anything urgent that does not change public interface in an incompatible way. By incompatible changes i mean:
- changing path to `main.go`
- removing/renaming arguments that third-parties may rely on.

Maybe we should introduce features as batches consisting of multiple PRs and bump minor version or create a dev branch that is merged once in a while. Either way, this will facilitate merging fixes into the main at any time without releasing new features.

What do you think, @xvzc?

**Comment by xvzc** [comment]
First of all, sorry for your inconvinience. I wasn't aware of that renaming path to main.go occur those problem. And i'be also thought of creating dev branch and use main branch only for fixes, but how could we make people basically fork the dev branch by default? We can write a `CONTRIBUTION.md` or maybe somehow?

**Comment by Ledorub** [comment]
I will think about it and reply later. Can we bump minor version to update Homebrew formula? It's not urgent.

**Comment by xvzc** [comment]
you want the new release with the version 0.11.0?

**Comment by xvzc** [comment]
Got it. then for now we will just maintain only the main branch right?

**Comment by Ledorub** [comment]
I suggest so.
