### ISSUE TITLE
How change default address?

### ISSUE THREAD

**Issue by vladhelios** [xvzc/SpoofDPI#207]
### Version

v0.10.11

### Operating System

Sonoma

### How are you running SpoofDPI?

spoofdpi

### Description

<img width="886" alt="image" src="https://github.com/user-attachments/assets/7fe9d83e-5299-40bd-8825-2ed180323285">

is it possible to change this address?

**Comment by xvzc** [comment]
You can give --port option. 
spoofdpi --port 8081 would work.
