### ISSUE TITLE
exit status 4

### ISSUE THREAD

**Issue by herenickname** [xvzc/SpoofDPI#21]
macOS 12.2.1

➜  ~ spoof-dpi -debug
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██
███████ ██       ██████   ██████  ██      ██████  ██      ██

• PORT  : 8080
• DNS   : 8.8.8.8
• DEBUG : true

FATA[2022-03-14T05:22:41+03:00] exit status 4

**Comment by xvzc** [comment]
Are you using wired network?

**Comment by MrSandManFM** [comment]
Having the same problem. I'm using wired network, ethernet interface. System is MacOS 10.13.6.

**Comment by xvzc** [comment]
There was an issue when there are spaces within the name of the network interface.
Fixed in Release v0.52, closing.
