### ISSUE TITLE
init in nixpkgs

### ISSUE THREAD

**Issue by s0me1newithhand7s** [xvzc/SpoofDPI#211]
### Description

hi,
i'm hand7s (hands), nixpkgs contributor and oss enthusiast. 
nice to meet you, dear @xvzc, and i'm appreciate job that you and others done. and to extend this package popularity and provide some help i'm asking about packaging in nixpkgs. if you interested in - let me know. i'll provide my vision on packaging, or package it myself.

P.S.
feel free to chat with me on russian and english as i understand both well enough. :)

**Comment by Askodon** [comment]
пакетирование в nixpkgs помогло бы многим, тот же zapret пока не очень хорошо поддаётся пакетированию в силу гвоздей в скриптах.

**Comment by xvzc** [comment]
Hi, Thank you for reaching us. I don't have any experience in nixpkg, then what's your plan to package this out?

**Comment by s0me1newithhand7s** [comment]
> Hi, Thank you for reaching us. I don't have any experience in nixpkg, then what's your plan to package this out?

nixpkgs have native tools for Golang binary building. for now - you can check my [PR](https://github.com/NixOS/nixpkgs/pull/337795) and review it or even approve, as you wish. for the future - i will maintain this package (in case of merge) and let you know about related issues.

**Comment by s0me1newithhand7s** [comment]
> пакетирование в nixpkgs помогло бы многим, тот же zapret пока не очень хорошо поддаётся пакетированию в силу гвоздей в скриптах.

у меня самого родилась идея пакеткуть ибо zapret прям мощно так насрал. :D

**Comment by xvzc** [comment]
Sadly i don't really understand your PR at all because i have no exprience in nix 😢. Thanks for your work anyways!

**Comment by s0me1newithhand7s** [comment]
> Sadly i don't really understand your PR at all because i have no exprience in nix 😢. Thanks for your work anyways!

and you don't need to, bc main part of job done by me.
you are welcome, my friend.

**Comment by s0me1newithhand7s** [comment]
@xvzc and yes, can you inform me about new versions pls? :D

**Comment by xvzc** [comment]
@s0me1newithhand7s what do you mean? do you want to get notified on every new release?

**Comment by Ledorub** [comment]
@s0me1newithhand7s, on the repo main page you can click on the `Watch` dropdown arrow > `Custom` > check `Releases`.

**Comment by s0me1newithhand7s** [comment]
> @s0me1newithhand7s what do you mean? do you want to get notified on every new release?

sorry for missinformation, i mean "stable"

> @s0me1newithhand7s, on the repo main page you can click on the `Watch` dropdown arrow > `Custom` > check `Releases`.

thx!! i rly need it :D

**Comment by s0me1newithhand7s** [comment]
merged
