### ISSUE TITLE
How use spoofdpi as system dns-doh?

### ISSUE THREAD

**Issue by NektoNektovich** [xvzc/SpoofDPI#215]
### Version

0.10.12

### Operating System

debian 12

### How are you running SpoofDPI?

I put spoofdpi in /usr/bin

### Description

Hello. I want to use spoofdpi as system dns-doh. I do it in Linux like this: spoofdpi --enable-doh --dns-addr string "https://dns.adguard-dns.com/dns-query", but it doesn’t work, Google dns still goes :( please tell me how gotta do it right

**Comment by Ledorub** [comment]
`spoofdpi --enable-doh --dns-addr ` ~~string~~ `"https://dns.adguard-dns.com/dns-query"`
