### ISSUE TITLE
What workaround methods are used ?

### ISSUE THREAD

**Issue by sanek184** [xvzc/SpoofDPI#217]
### Version

v0.11.1

### Operating System

Windows

### How are you running SpoofDPI?

SpoofDPI.exe -port 10900 -window-size 2

### Description

I wanted to ask what bypass methods are used by default. Sites open well on tls1.2, which means they are sending fakes, I would like to know which ones. Preferably with arguments using the example of any analogue. Thank you

**Comment by xvzc** [comment]
We don't send any fake packets. We just do TCP level fragmentaion of client hello packet.

**Comment by sanek184** [comment]
> We don't send any fake packets. We just do TCP level fragmentaion of client hello packet.

Something similar to wrong SEQ/ACK ?

**Comment by xvzc** [comment]
maybe `--window-size 2` option is the hint. because spoofdpi doesn't work in my country without `--window-size 1` option. if you give low window size, it can cause some kind a race condition on the DPI machine.
