### ISSUE TITLE
Can't change port

### ISSUE THREAD

**Issue by alotofthingstodo** [xvzc/SpoofDPI#223]
### Version

0.11.1

### Operating System

Ubuntu 24.04

### How are you running SpoofDPI?

Through the command spoofdpi in Terminal. I installed it through curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s linux-amd64

### Description

My wifi blocks all but a few ports and I don't have a way to change it, so I tried to change ports in Spoofdpi settings but got this error.
spoofdpi -port int 80
invalid value  "int" for flag -port: parse error.

**Comment by Ledorub** [comment]
`int` is a hint of the type of a value you are supposed to provide, you don't have to include it. `-port 80`

**Comment by xvzc** [comment]
I think we should add some example usage..

**Comment by alotofthingstodo** [comment]
> I think we should add some example usage..

Please explain to me how use it, I'm a complete noob.

**Comment by alotofthingstodo** [comment]
> `int` is a hint of the type of a value you are supposed to provide, you don't have to include it. `-port 80`, where 80 is an integer.

I got it, but there is an error.

FTL 2024-08-30T11:11:53+03:00 [PROXY] error creating listener: listen tcp 127.0.0.1:80: bind: permission denied

**Comment by Ledorub** [comment]
Try with port greater than 1024.

**Comment by alotofthingstodo** [comment]
> Try with a port greater than 1024.

It works, but it's of no use to me, because my wifi owner blocked access to all ports apart from 80 and 443.

**Comment by Ledorub** [comment]
You need elevated privileges to bind to ports in range 1-1023.

**Comment by alotofthingstodo** [comment]
> You need elevated privileges to bind to ports in range 1-1023.

Please explain to me how to get them.

**Comment by Ledorub** [comment]
Prepend `sudo`, it will ask you for root password.

**Comment by alotofthingstodo** [comment]
> Prepend `sudo`, it will ask you for root password.

I got elevated rights and set up port 80 successfuly

But when I enter google-chrome --proxy-server="http://127.0.0.1:8080" I got this error 

^X^Croot@Vivobookgoogle-chrome --proxy-server="http://127.0.0.1:8080"080"
[26594:26594:0830/113424.487498:ERROR:zygote_host_impl_linux.cc(99)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by alotofthingstodo** [comment]
> Prepend `sudo`, it will ask you for root password.

I got elevated rights and set up ort 80 successfully but when I enter google-chrome --proxy-server="http://127.0.0.1:80" I got the error below.

root@Vivobook:~# google-chrome --proxy-server="http://127.0.0.1:80"
[28252:28252:0830/114134.539163:ERROR:zygote_host_impl_linux.cc(99)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
root@Vivobook:~#

**Comment by xvzc** [comment]
for your safety, I don't recommend you running spoofdpi with port number under 1024, which requires root permission.

**Comment by alotofthingstodo** [comment]
> Prepend `sudo`, it will ask you for root password.

That's what I get with FIrefox.

![Uploading Screenshot from 2024-08-30 12-37-38.png…]()
