### ISSUE TITLE
How to disable auto system-proxy on MAC

### ISSUE THREAD

**Issue by alexarcherr** [xvzc/SpoofDPI#235]
### Version

11.1

### Operating System

MacOS

### How are you running SpoofDPI?

 spoofdpi --enable-doh --window-size 0 -banner false -system-proxy false

### Description

How to disable automatic system-level proxy?
 -system-proxy false - doesn't work

**Comment by hempalex** [comment]
try -system-proxy=false -banner=false

**Comment by alexarcherr** [comment]
Please correct CLI description in README, please!

**Comment by alexarcherr** [comment]
yes, it works!

**Comment by hempalex** [comment]
spoofdpi uses standard flag package, you can refer to go docs
https://pkg.go.dev/flag#hdr-Command_line_flag_syntax

**Comment by xvzc** [comment]
@Ledorub As you know, We've been having so many issues related with `--system-proxy`. Will it be better to set  the default value of the option to `false`?

**Comment by Ledorub** [comment]
The problem I see with setting `system-proxy` to false by default is that people will have to know that they are expected to configure the apps to use proxy. Can it lead to more questions like "I launched the SpoofDPI, but the site X still doesn't work"?

**Comment by xvzc** [comment]
@Ledorub I also partly agree with you. However, i think it's better to let people know about what `system-proxy` does and let them use the option on their need. Just in case of some issues like #213, which i think is more critical.
