### ISSUE TITLE
DNS. Add ability to disable ipv6 resolution

### ISSUE THREAD

**Issue by LiquidTheDangerous** [xvzc/SpoofDPI#239]
### Description

I don't have ipv 6 configured on some devices. I want to be able to prevent the DNS resolver from querying the service for ipv 6 addresses.

>DBG 2024-09-07T17:45:19+05:00 3a5da414-83c64f7b-25971626-f9fa4506 [DNS] resolving www.google.com using general resolver(8.8.8.8:53)
DBG 2024-09-07T17:45:19+05:00 3a5da414-83c64f7b-25971626-f9fa4506 [DNS] resolved 2a00:1450:4010:c05::69 from www.google.com in 72 ms
DBG 2024-09-07T17:45:19+05:00 3a5da414-83c64f7b-25971626-f9fa4506 [HTTPS] dial tcp [2a00:1450:4010:c05::69]:443: connect: network is unreachable

```bash
ping -6 google.com
> ping: connect: Network is unreachable
```

**Comment by Ledorub** [comment]
I see two things that are worth discussing:
1. Maybe we should measure how big of a performance gain this change would provide for users with IPv4-only machines. Would it be really noticeable?
2. To make SpoofDPI more user-friendly, specifically for less tech-savvy users, I think that IPv6 resolution should be on by default. But we can add `dns-ipv4` or `dns-ipv4-only` option, or something alike.

@xvzc

**Comment by LiquidTheDangerous** [comment]
@Ledorub see this PR #240

**Comment by Ledorub** [comment]
I saw it, but decided to express my thoughts in the issue.

**Comment by Ledorub** [comment]
I think that #240 was merged a bit too soon. @LiquidTheDangerous, could you please update the main `README.md` and those in `_docs/`? As a separate PR.

**Comment by xvzc** [comment]
Oh i forgot about the docs. Let me do this as a quick push to the main.
