### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by SwShard** [xvzc/SpoofDPI#247]
### Version

v0.12.0

### Operating System

Android 10

### How are you running SpoofDPI?

adguard, spoofdpi in termux (it doesn't matter which startup arguments. Termux traffic is not routed through adguard)

### Description

Hello, Is there android support in the program? I tried to run it via termux (with and without sudo) and set up a proxy in the adguard program in https and/or http mode (I also tried it in firefox nightly).
Spoofdpi in the terminal generates [PROXY] and [HTTPS] errors (depending on whether https or http is selected). Nothing is loaded at the same time

**Comment by LiquidTheDangerous** [comment]
I use this scenario.
1. Run Spoof-dpi via termux
![1](https://github.com/user-attachments/assets/09f129f8-e11f-469f-8e95-bf0225194c36)
2. Setting up wi-fi proxy settings.
![2](https://github.com/user-attachments/assets/b696690a-88c7-418d-8ca8-fc8f1308a301)
3. Or setting up APN for mobile network
![3](https://github.com/user-attachments/assets/4faeea51-ef71-40e5-84ff-b8b0b182b197)

**Comment by LiquidTheDangerous** [comment]
@SwShard If there are errors in the logs, you can attach them. Make sure you run with `-debug`.

**Comment by SwShard** [comment]
@LiquidTheDangerous Using a proxy in the Wi-Fi settings is frankly useless, because it says in plain text that it only works with browsers. Proxying through adguard also allows distribute this to any application.
But even if i use the option you suggested, it still gives errors and does not load anything in browser. Adguard was disabled at the same time:

```DBG 2024-09-16T20:28:25Z 16fba31b-7ac56d83-8ffb553e-cdee5802 [DNS] resolving connectivitycheck.gstatic.com using general resolver(9.9.9.9:53)
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [DNS] resolved 142.250.184.228 from www.google.com in 102 ms
DBG 2024-09-16T20:28:25Z 16fba31b-7ac56d83-8ffb553e-cdee5802 [DNS] resolved 108.177.127.94 from connectivitycheck.gstatic.com in 106 ms
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] new connection to the server 192.168.0.197:49984 -> www.google.com
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] sent connection established to 127.0.0.1:38532
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] client sent hello 567 bytes
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] writing chunked client hello to www.google.com
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] window-size: 0
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] using legacy fragmentation
DBG 2024-09-16T20:28:25Z 16fba31b-7ac56d83-8ffb553e-cdee5802 [HTTP] new connection to the server 192.168.0.197:37129 -> connectivitycheck.gstatic.com
DBG 2024-09-16T20:28:25Z 16fba31b-7ac56d83-8ffb553e-cdee5802 [HTTP] error reading from connectivitycheck.gstatic.com: EOF
DBG 2024-09-16T20:28:25Z 16fba31b-7ac56d83-8ffb553e-cdee5802 [HTTP] error reading from 127.0.0.1:38534: read tcp 127.0.0.1:8080->127.0.0.1:38534: use of closed network connection
DBG 2024-09-16T20:28:25Z 16fba31b-7ac56d83-8ffb553e-cdee5802 [HTTP] closing proxy connection: 127.0.0.1:38534 -> connectivitycheck.gstatic.com
DBG 2024-09-16T20:28:25Z 16fba31b-7ac56d83-8ffb553e-cdee5802 [HTTP] closing proxy connection: connectivitycheck.gstatic.com -> 127.0.0.1:38534
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] error reading from www.google.com: EOF
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] error reading from 127.0.0.1:38532: read tcp 127.0.0.1:8080->127.0.0.1:38532: use of closed network connection
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] closing proxy connection: 127.0.0.1:38532 -> www.google.com
DBG 2024-09-16T20:28:25Z 6de8aa5a-957c0b70-e1815691-0052d9a0 [HTTPS] closing proxy connection: www.google.com -> 127.0.0.1:38532

**Comment by LiquidTheDangerous** [comment]
@SwShard In my case it works as well as on Linux. Youtube, and any other applications uses this system settings

**Comment by LiquidTheDangerous** [comment]
@SwShard Make sure termux session can run in the background, android shouldn't kill it
