### ISSUE TITLE
SpoofDPI doesn't work in Russia

### ISSUE THREAD

**Issue by Smerch01** [xvzc/SpoofDPI#261]
### Version

0.12.0

### Operating System

Mac OS Sequoia 15

### How are you running SpoofDPI?

WIth Terminal

### Description

-

**Comment by wassalam01** [comment]
Macos 13.6.9
Run with no pass any settings. Youtube work for example.
`INF 2024-09-29T21:27:59+03:00 [PROXY] created a listener on port 8080`

**Comment by Smerch01** [comment]
Nothing changed, maybe this is connected with my version of mac os

**Comment by Ekzar** [comment]
Debian 12 (bookworm)
Run with no pass any settings.
A similar problem started just a few hours ago.

**Comment by doroved** [comment]
@Smerch01 
I just posted my simple solution that can proxy different by filtered domains and bypasses youtube blocking, try it.
https://github.com/doroved/proxer

**Comment by dzhizhkin** [comment]
Mac os Sonoma 14.7 (23H124) also doesnt work with YouTube

**Comment by lindenes** [comment]
Arch  youtube not work in russia

**Comment by segery** [comment]
I had to switch to byedpi. Arch linux.

**Comment by Ledorub** [comment]
There is already an ongoing discussion in #258.
