### ISSUE TITLE
SPOOF-DPI error creating listener. bind: address already in use

### ISSUE THREAD

**Issue by darkisan** [xvzc/SpoofDPI#263]
### Version

spoofdpi v0.12.0

### Operating System

MacOS Sequoia 15.0

### How are you running SpoofDPI?

by the command in terminal
~/.spoofdpi/bin/spoofdpi

### Description

I used spoof-dpi for month (august-september) and it works fine. But on 27~ September (I was on macOS Sonoma) it stopped  working. It shows proxy error.

**[PROXY] error creating listener: listen tcp 127.0.0.1:8080: bind: address already in use**

When I start spoof dpi with options (port changing)  (_-port 8090_) it starts, but works veeeery slow. So, I add new option (_-window-size 1_) and spoof-dpi started working a little bit better, but YouTube videos still not loading. (I tried to change window-size for different values, but there is no better way than 1 as value)

<img width="565" alt="Снимок экрана 2024-10-03 в 12 48 12" src="https://github.com/user-attachments/assets/58dfc9e9-5e0a-4ce4-8a90-48061f49b198">

**Comment by xvzc** [comment]
There may be some other process that's listening on the port 8080

**Comment by darkisan** [comment]
How can I check which process is using this port? Startup on other ports is slower for some reason

**Comment by anghei** [comment]
> How can I check which process is using this port? Startup on other ports is slower for some reason

You may try run `nmap localhost` to see which ports are open and by which service on

**Comment by platon-p** [comment]
You can run spoof-dpi on another port in order to avoid conflict
```
spoof-dpi -port 8888
```
