### ISSUE TITLE
SpoofDPI do not working

### ISSUE THREAD

**Issue by Danil1046** [xvzc/SpoofDPI#271]
### Version

12

### Operating System

macOS Sequoia 15.0.1

### How are you running SpoofDPI?

in the terminal:

```
curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh
export PATH=$PATH:~/.spoof-dpi/bin
spoof-dpi
```

### Description

Hello, yesterday i started spoofdpi as usual in terminal, and i could see previews, each frame second by second and loading website was pretty fast, but i can't watch the videos. Can somebody help me? Maybe you've got a link on the same issue.

**Comment by thetekst** [comment]
Look at this [issue](https://github.com/xvzc/SpoofDPI/issues/270) from september 10

**Comment by yenyasinn** [comment]
Duplication of https://github.com/xvzc/SpoofDPI/issues/270

**Comment by AntonyBenjiro** [comment]
switch to byedpi:
https://github.com/hufrea/byedpi/issues/17#issuecomment-2413102589

**Comment by Gen5551** [comment]
Со всеми вопросами, обращайтесь в генпрокуратуру через обычную почту.

**Comment by Danil1046** [comment]
Hi. Look at this https://github.com/xvzc/SpoofDPI/issues/270 from October 10
