### ISSUE TITLE
Problem with spoof-dpi@latest package for go install

### ISSUE THREAD

**Issue by GlulkAlex** [xvzc/SpoofDPI#277]
### Version

v0.10.10

### Operating System

Ubuntu 22.04.5 LTS

### How are you running SpoofDPI?

running with: `$ spoof-dpi`
was installed according to https://github.com/xvzc/SpoofDPI/blob/main/_docs/INSTALL.md?plain=1#L41
`go install github.com/xvzc/SpoofDPI/cmd/spoofdpi@latest`

### Description

I see this output:
```bash
$ go install github.com/xvzc/SpoofDPI/cmd/spoof-dpi@latest
go: github.com/xvzc/SpoofDPI/cmd/spoof-dpi@latest: module github.com/xvzc/SpoofDPI@latest found (v0.12.0), but does not contain package github.com/xvzc/SpoofDPI/cmd/spoof-dpi
```
while having 
[Version: v0.10.10 ](https://pkg.go.dev/github.com/xvzc/SpoofDPI/cmd/spoof-dpi?tab=versions)Latest 
Published: Aug 20, 2024

Will it be updated to newer versions eventually ?

**Comment by nikpivkin** [comment]
need `go install github.com/xvzc/SpoofDPI/cmd/spoofdpi@latest`

but you're trying `go install github.com/xvzc/SpoofDPI/cmd/spoof-dpi@latest`

**Comment by GlulkAlex** [comment]
Thank you @nikpivkin ! :handshake: My bad . after you mentioned correct path, i also noticed my mistake (extra `-` in my own post) . Works like a charm .
