### ISSUE TITLE
Could you make a docker image?

### ISSUE THREAD

**Issue by KimPig** [xvzc/SpoofDPI#28]
Hello
I'm looking for a DPI bypass tool.
GreenTunnel, etc. are not working in Korea, and I was wondering if this tool works, but I couldn't run it properly because I didn't have enough basic knowledge about Linux.

```
root@TEST:/# spoof-dpi
-ash: /root/.spoof-dpi/bin/spoof-dpi: No such file or directory
```

So, do you have any thoughts of creating a Docker image?

It will be much easier to execute.

**Comment by xvzc** [comment]
안녕하세요. SpoofDPI는 얼마전 한국에서 동작하지 않게 되었습니다. 비슷한 계열의 툴 모두 동작하지 않은 것으로 알고있습니다. Linux를 사용중이시라면 iptables를 사용해서 RST 패킷을 드랍하는 방식으로 사용하시면 될 것 같습니다.

**Comment by kimpig** [comment]
시놀로지 나스에 적용시킬려고 했는데, 아무래도 제가 건들 범주는 아닌가 봅니다.
새로운 툴이 나올때까지 기다려야 겠네요. 답변 감사드립니다.
