### ISSUE TITLE
Support for more platforms and architectures ?

### ISSUE THREAD

**Issue by Baltazar500** [xvzc/SpoofDPI#29]
Hi.

The number of binaries in releases is very small. Is it possible to increase the number of supported platforms? "Linux" version did not start for me

>spoof-dpi --help
>-bash: /bin/spoof-dpi: cannot execute binary file

Is it an x64 binary? I am using (old) x86 linux i386/i586. 

We also need binaries for armv7 (android), arm64-v8a (android), windows (x64/x86)

**Comment by xvzc** [comment]
Maybe you better just build your own.
```
GOOS=${YOUR_OS} GOARCH=${YOUR_ARCH} go build -ldflags='-w -s' github.com/xvzc/SpoofDPI/cmd/spoof-dpi
```

GOARCH variable should be your architecture like amd64
