### ISSUE TITLE
Options to enable DoT and DoH domain?

### ISSUE THREAD

**Issue by debpalash** [xvzc/SpoofDPI#32]
e.g dns.nextdns.io dns.adguard.com

**Comment by xvzc** [comment]
are 'nextdns.io' or 'dns.adguard' ddns ?

**Comment by debpalash** [comment]
I'm not sure they are. But they are "Dns over HTTP" endpoints. Where 1.1.1.1 is not filtered, but e.g dns.nextdns.io, dns.adguard.com comes with configurable options to filter custom lists. I guess i can just use their dns server ip's.
