### ISSUE TITLE
SpofDPI won't work: dial tcp 8.8.8.8:443: connect: no route to host

### ISSUE THREAD

**Issue by AlexVT100** [xvzc/SpoofDPI#33]
Hi,

SpoofDPI won't work for me (and never worked). Any connection attempt to any site always gives the same errors:

ERRO[2022-08-07T15:09:15+03:00] [HTTPS DOH] Error looking up for domain: www.google.com Post "https://8.8.8.8/dns-query": dial tcp 8.8.8.8:443: connect: no route to host 
ERRO[2022-08-07T15:09:18+03:00] [HTTPS DOH] Error looking up for domain: www.google.com Post "https://8.8.8.8/dns-query": dial tcp 8.8.8.8:443: connect: no route to host 
...

Please advice!

Thanks!

**Comment by xvzc** [comment]
which command did you use to run it?

**Comment by AlexVT100** [comment]
```
u0@pc:~> cd .spoof-dpi/bin/
u0@pc:~/.spoof-dpi/bin> ./spoof-dpi 

• ADDR  : 127.0.0.1
• PORT  : 8080
• DNS   : 8.8.8.8
• DEBUG : false

INFO[2022-08-07T22:02:06+03:00] Created a listener on : 8080                 

```
OpenSUSE Tumbleweed

Thanks!

**Comment by xvzc** [comment]
did u try any other dsn sercer either? like 1.1.1.1 for example

**Comment by Sly-Little-Fox** [comment]
8.8.8.8 seems to be blocked in your country

**Comment by jerry-as** [comment]
@Sly-Little-Fox never thought about it but yeah @AlexVT100  it possibly is

**Comment by Sly-Little-Fox** [comment]
> @Sly-Little-Fox never thought about it but yeah @AlexVT100 it possibly is

Used to such errors because of how many services are blocked in my country
