### ISSUE TITLE
Support IPV6

### ISSUE THREAD

**Issue by aglu** [xvzc/SpoofDPI#35]
This application dont's support ipv6-network and ipv6-sites.

1. Ipv6-address in dns is not valid in app
`spoof-dpi --port=8000 --dns=[2606:4700:4700::1111]
zsh: no matches found: --dns=[2606:4700:4700::1111]`
2. DNS request with AAAA records only throws an error. 
`ERRO[2023-01-23T01:55:19+03:00] [HTTPS DOH] Error looking up for domain: ipv6.ams2.test-ipv6.com  couldn't resolve the domain `
3. App recognizes ipv6-host as domain name and throws error. Ipv6-site is not available.
`ERRO[2023-01-23T01:55:33+03:00] [HTTPS DOH] Error looking up for domain: 2001:470:1:18::115 Name error `

**Comment by xvzc** [comment]
Will supporting system dns solve this issue?

**Comment by aglu** [comment]
Need support ipv6-dns and processing AAAA-records. In IPv6-only (with NAT64) network app dont'worked.

PS. Maybe this ticket market as improvements

**Comment by Albonycal** [comment]
Yea IPv6 support would be nice

**Comment by xvzc** [comment]
Guys I really want to add this feature as an enhancement but lately i'm quite busy to work on it. Sorry.

**Comment by Albonycal** [comment]
It's fine :D

**Comment by Ledorub** [comment]
Done in [v0.10.10](https://github.com/xvzc/SpoofDPI/releases/tag/v0.10.10).
