### ISSUE TITLE
exit status 14

### ISSUE THREAD

**Issue by mertcangokgoz** [xvzc/SpoofDPI#37]
I'm using macOS Ventura 13.2.1 and getting an error. I installed it via go.

```
mertcangokgoz@Macbook ~ » spoof-dpi -debug
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██ 
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██ 
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██ 
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██ 
███████ ██       ██████   ██████  ██      ██████  ██      ██ 

• ADDR  : 127.0.0.1
• PORT  : 8080
• DNS   : 8.8.8.8
• DEBUG : true

FATA[2023-03-08T08:30:21+03:00] exit status 14
```

**Comment by xvzc** [comment]
which version of go are u using

**Comment by mertcangokgoz** [comment]
Hello @xvzc 

I tried the installation with the command line and got the same error. I am using the latest version of golang.

**Comment by xvzc** [comment]
Sorry for the late reply. Please tell me the version of your go

**Comment by labac-p** [comment]
comment `SetOsProxy` then it works

**Comment by xvzc** [comment]
@labac-p  There might have been something worng with your OS permission i think.

**Comment by labac-p** [comment]
Probably due to enabling this option.
Feature request: add auto-setting proxy flag ?

<img width="827" alt="image" src="https://github.com/xvzc/SpoofDPI/assets/100670919/3a9d5300-51de-4f7f-bf84-ca172ea8c666">

**Comment by Fyne5** [comment]
Me too, I'm running it on my MacOS 12.7.1 and installed SpoofDPI by binary. So, do I need to install Go?

**Comment by evgeniyGusev** [comment]
I had same problem too. But running with sudo has fixed it) `sudo spoof-dpi`

**Comment by mrongSubho** [comment]
Faced the same issue on Sonoma 14.5 using curl.

**Comment by Zzoomrus** [comment]
> I had same problem too. But running with sudo has fixed it) `sudo spoof-dpi`

Solve problem on m1. On intel mac works without sudo

**Comment by drduse** [comment]
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██ 
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██ 
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██ 
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██ 
███████ ██       ██████   ██████  ██      ██████  ██      ██ 

• ADDR    : 127.0.0.1
• PORT    : 8080
• DNS     : 8.8.8.8
• DEBUG   : false

FATA[2024-08-03T19:36:15+03:00] exit status 4                                
                                 
go version go1.22.5 darwin/amd64

**Comment by Ledorub** [comment]
In [0.10.11](https://github.com/xvzc/SpoofDPI/releases/tag/0.10.11) those exit codes were replaced with more informative messages.
