### ISSUE TITLE
not working in iran

### ISSUE THREAD

**Issue by shervin-chavoshi** [xvzc/SpoofDPI#41]
unfortanetly it doesnt work in iran
![Uploading image.png…]()

**Comment by shervin-chavoshi** [comment]
![notworking](https://user-images.githubusercontent.com/130045597/235505988-4b79c858-17b3-405f-b89a-5ed645bfeb94.png)

**Comment by xvzc** [comment]
Maybe your client hello packets get reassembled in you country

**Comment by xvzc** [comment]
I couldn't find a way yet to do something like what GoodbyeDPI does on linux system. Sorry.

**Comment by tinkerbell1268** [comment]
i got this error on mac os catalina:
[HTTPS DOH] Error looking up for domain: www.google.com Post "https://8.8.8.8/dns-query": net/http: TLS handshake timeout 
please add option to choose dns type similar GreenTunnel ("https", "tls")
