### ISSUE TITLE
HTTPS not working when using with Opnsense/pfsense

### ISSUE THREAD

**Issue by bubundas17** [xvzc/SpoofDPI#42]
Hi,
I am trying to use it with opnsense router to enable DPI spoofing network wide. (Just Like GoodbyeDPI)
When using it via firewall Although All http traffic  working correctly, the problem is with HTTPS traffic. 
Websites are not opening correctly. it ended up with "Unsupported method:" error.

Will it be possible to port this project to account for this use case?
Firewall:
![image](https://github.com/xvzc/SpoofDPI/assets/26280146/d7d40219-dc73-463d-a3db-d092a9d98278)

Error:
![image](https://github.com/xvzc/SpoofDPI/assets/26280146/63b79412-c60c-4e5d-965c-1ec4589e8534)

**Comment by xvzc** [comment]
The proxy part of the logs that u provided looks little bit wierd.
It should look like below.

CONNECT ru.linkedin.com:443 HTTP/1.1
Host: ru.linkedin.com
Proxy-Connection: keep-alive
Connection: keep-alive
 
I think maybe there's some kinda encoding issue with your environment?
