### ISSUE TITLE
Some sites don't open in Russia

### ISSUE THREAD

**Issue by rakleed** [xvzc/SpoofDPI#47]
Some sites do not open in Russia, for example, `adguard.com`. When using a VPN/proxy, they open. Can you improve DPI bypass? Let me know if you need logs or other information.

**Comment by xvzc** [comment]
Yeah this is a known issue. I'm still trying to figure out what causes this issue. Sorry that i couldn't give you any solution.

**Comment by xvzc** [comment]
Would u try again with the latest release? Just wanna check if this is related with the issue #46

**Comment by rakleed** [comment]
Still, for example, https://adguard.com does not open.
