### ISSUE TITLE
Doesn't seem to handle network interface switching effectively

### ISSUE THREAD

**Issue by felikcat** [xvzc/SpoofDPI#50]
<img width="471" alt="Screenshot 2023-09-08 at 19 30 35" src="https://github.com/xvzc/SpoofDPI/assets/29991266/87b8686a-d6f0-45ae-9f45-523ce859cae3">

I swap between an ethernet adapter connected to my cable internet, and a WiFi that connects to a hotspot my Pixel phone is hosting.

`networksetup -listallhardwareports`:
```
Hardware Port: USB 10/100/1G/2.5G LAN
Device: en6
Ethernet Address: no

Hardware Port: Wi-Fi
Device: en0
Ethernet Address: no
```

After switching network interfaces, I have to exit SpoofDPI, then either leave it closed or re-open it to get the DNS resolution working again.

*NOTE*: SpoofDPI does automatically set the proxy settings for both interfaces, but the DNS resolve issue persists.

**Comment by xvzc** [comment]
It's because it doesn't keep watching the changes of network interface. It just adjust the proxy setting for current network interface on startup, and never changes the setting.
