### ISSUE TITLE
upload or download image and file not work using whatsapp web/desktop

### ISSUE THREAD

**Issue by warnacloud** [xvzc/SpoofDPI#51]
I have an issue sending or download images and files using WhatsApp. My environment is using WhatsApp Desktop from the Microsoft Store.

this is example for upload retry
<img width="371" alt="image" src="https://github.com/xvzc/SpoofDPI/assets/54879991/8ec4fa73-1042-4833-8619-29ad6b4fce6f">

this is example for stuck download

<img width="296" alt="image" src="https://github.com/xvzc/SpoofDPI/assets/54879991/9ed1f214-92fd-4165-a710-66711b2b1138">

**Comment by jerry-bmlabs** [comment]
Which OS?

**Comment by xvzc** [comment]
Which OS?

**Comment by warnacloud** [comment]
> Which OS?

windows

**Comment by xvzc** [comment]
I'm sorry but this project wasn't actually developed for windows environment

**Comment by warnacloud** [comment]
Windows is only as a client, I installed the dpi on the ubuntu server.

**Comment by xvzc** [comment]
Tell me how u set up the proxy config and which version if SpoofDpi you are using

**Comment by warnacloud** [comment]
i'm using latest version `Release v0.8 `
the setup just set proxy settings and set server ip and port

**Comment by warnacloud** [comment]
@xvzc any update?
