### ISSUE TITLE
Error when running on libreelec

### ISSUE THREAD

**Issue by HyperSmartian** [xvzc/SpoofDPI#52]
After installing the script through curl on my rpi 3 running libreelec 11 through ssh i got below response

Successfully installed SpoofDPI.
Please add the line below to your rcfile(.bashrc or .zshrc etc..)

>>    export PATH=$PATH:~/.spoof-dpi/bin

which is expected

but when i tried to run spoof-dpi by

~/.spoof/bin/spoof-dpi

I got the below error
 /storage/.spoof-dpi/bin/spoof-dpi: line 1: syntax error: unexpected end of file (expecting ")")

Please let me know at the earliest a solution for this as i've tried the only other option of running green-tunnel on docker hogs memory and freezes the rpi.

# How To Reproduce?
Install and run on rpi running libreelec os.

**OS**: Libreelec 

**Version**:11

**Comment by xvzc** [comment]
I don't have any device that runs libreelec os. If you tell me the way how i can test this project on libreelec, I will follow your instruction.
