### ISSUE TITLE
Question: Is it possible to use SpoofDPI on top of Shadowsocks?

### ISSUE THREAD

**Issue by talentlessguy** [xvzc/SpoofDPI#53]
From what I understand it's possible to deploy SpoofDPI on a server and put up a custom host and port - but is it possible to make it work on top of ShadowSocks?

**Comment by admarty** [comment]
This is my implementation on a vmess server side, spoof-dpi listen on localhost:8080 :
{
  "log": {
    "loglevel": "none",
    "access": "/dev/null",
    "error": "/dev/null"
  },
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "outboundTag": "DPI-bypass",
        "port": "80,443"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "${listen_addr}",
      "port": 1234,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "${uuid}"
          }
        ]
      },
      "streamSettings": {
        "${nw}": "ws",
        "wsSettings": {
          "path": "/vmess"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    },
    {
      "tag": "DPI-bypass",
      "protocol": "http",
      "settings": {
        "servers": [
          {
            "address": "127.0.0.1",
            "port": 8080
          }
        ]
      }
    }
  ]
}
