### ISSUE TITLE
Not working on ARM based system (Linux)

### ISSUE THREAD

**Issue by shaper12340w** [xvzc/SpoofDPI#54]
As I described it on title, it's not working on ARM64 like raspberry pi.

`Dynarec for ARM64, with extension: ASIMD CRC32 PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 32 entries
Box64 with Dynarec v0.2.5 4c7ac85a built on Nov 22 2023 06:29:18
BOX64: Didn't detect 48bits of address space, considering it's 39bits
Counted 60 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/home/shaper/.local/bin/:/usr/local/sbin/:/usr/local/bin/:/usr/sbin/:/usr/bin/:/sbin/:/bin/:/usr/local/games/:/usr/games/
Looking for ./spoof-dpi
Rename process to "spoof-dpi"
20911|BOX64: Warning, calling Signal 11 function handler SIG_DFL
Unhandled signal caught, aborting
NativeBT: ./spoof-dpi() [0x34a0e558]
NativeBT: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7fb3b8d7bc]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(+0x809d0) [0x7fb3a009d0]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(gsignal+0x1c) [0x7fb39ba76c]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(abort+0xf0) [0x7fb39a74bc]
NativeBT: ./spoof-dpi() [0x34a0cdf8]
NativeBT: ./spoof-dpi() [0x34a0d510]
NativeBT: ./spoof-dpi() [0x34a0f024]
NativeBT: ./spoof-dpi() [0x34fd9f5c]
NativeBT: ./spoof-dpi() [0x349d5c7c]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(+0x27780) [0x7fb39a7780]
NativeBT: /lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98) [0x7fb39a7858]
NativeBT: ./spoof-dpi() [0x349d65fc]
EmulatedBT: /home/shaper/.spoof-dpi/bin/spoof-dpi+62100 [0x462100]
20911|SIGABRT @0x7fb3a009d0 (???(/lib/aarch64-linux-gnu/libc.so.6+0x809d0)) (x64pc=0x462100//home/shaper/.spoof-dpi/bin/spoof-dpi:"???", rsp=0x1007fe828, stack=0x100000000:0x100800000 own=(nil) fp=(nil)), for accessing 0x3e8000051af (code=-6/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000000000000 RSP-0x18:0x0000000000000000 RSP-0x10:0x0000000000000000 RSP-0x08:0x0000000000000000
RSP+0x00:0x0000000000000000 RSP+0x08:0x0000000000000000 RSP+0x10:0x0000000000000000 RSP+0x18:0x0000000000000002
RAX:0x0000000000000000 RCX:0x0000000002d83203 RDX:0x0000000017888915 RBX:0x0000000000010800 
RSP:0x00000001007fe828 RBP:0x0000000000000000 RSI:0x00000000008b64b0 RDI:0x0000000000001002 
 R8:0x0000000000000000  R9:0x0000000000000000 R10:0x0000000000000000 R11:0x0000000000000000 
R12:0x0000000000000000 R13:0x0000000000000000 R14:0x0000000000000000 R15:0x0000000000000000 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053`

please can you make this ARM version?

**OS**: raspbian (Debian (Linux))

**Version**:

# Additional context

**Comment by xvzc** [comment]
How did you install spoof-dpi?

**Comment by shaper12340w** [comment]
On the readme.md guide, I installed it by linux's installation guide.

**Comment by xvzc** [comment]
아 넵 반갑습니다. 혹시 직접 빌드하셨는지, 아니면 curl 기반의 설치를 하셨는지 여쭤봐도 될까요?

**Comment by shaper12340w** [comment]
curl 기반입니다

**Comment by xvzc** [comment]
흠 그러면 직접 빌드하는 방향으로 시도해보는 것이 좋을 것 같네요.

**Comment by vietvudanh** [comment]
You can always build it from source code. I build it for my Pi too.

**Comment by dontdieych** [comment]
self build working fine on Apple M2 MBA nixos

**Comment by Ledorub** [comment]
Seeing how there have not been any new reports related to the issue, I guess, I can close this.
