### ISSUE TITLE
Cannot access any website after changing network

### ISSUE THREAD

**Issue by huupoke12** [xvzc/SpoofDPI#56]
# Describe the bug
I cannot access any website after I change the network. I need to restart SpoofDPI to make it work again.

## Expected behavior
Access websites normally.

## Actual behavior
It keeps loading then timed out.

# How To Reproduce?
1. Start SpoofDPI.
1. Change current network to another access point (WiFi) or to wired network.
1. Access any website.

# Client information

**OS**: Fedora Workstation 39

**Version**: 0.8

# Additional context

**Comment by xvzc** [comment]
Did you set system proxy?

**Comment by huupoke12** [comment]
Yes, I have tried setting Firefox proxy only and system proxy only, and both doesn't work.
