### ISSUE TITLE
Question about the binaries

### ISSUE THREAD

**Issue by Rust1667** [xvzc/SpoofDPI#58]
hi, I notice there is some difference between the binary I downloaded from Releases and the binary I build with Go (I'm on Arch Linux)

- the one I downloaded from https://github.com/xvzc/SpoofDPI/releases/download/0.8/spoof-dpi-linux.tar.gz (4.9 MB): https://www.virustotal.com/gui/file/50d4865a71770d3cb3cceb4e53c8c5a1f5c2e4c179daca94912cadba077b3405/relations
- the one I build myself with go(8.0 MB) https://pixeldrain.com/u/bfoRMDjy: https://www.virustotal.com/gui/file/0d46a3fca6a31ed00658cc7eeadfaba7e6fbb9c18bbed727703ad99abeb15802/relations

the binary I downloaded from releases is contacting gnome and ubuntu domains, and the binary I built myself contacts none (according to VirusTotal)

does the one you build include anything different, or is it built with special settings, or telemetry?

**Comment by xvzc** [comment]
I don't think there will be so much difference in between binaries and the artifact that you built your own, except that the binaries use `golang:1.17-alpine`. Also, you can check the build process here. 
- https://github.com/xvzc/SpoofDPI/blob/main/build
- https://github.com/xvzc/SpoofDPI/blob/main/make-releases.sh

**Comment by Rust1667** [comment]
I see, thank you for the quick response.
Indeed I'm not building in the same OS or with the same compile flags so its normal is different binaries.
