### ISSUE TITLE
Handling of invalid requests results in infinite recursive call to the proxy

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [xvzc/SpoofDPI#61]
# Describe the bug

While testing code for https://github.com/xvzc/SpoofDPI/issues/31 I accidentally discovered that if you make a request to the proxy as a regular webpage (e.g. omit `--proxy` from `curl -v --proxy http://127.0.0.1:8080 *something*`) SpoofDPI goes into endless recursion querying self again and again.

## Expected behavior

SpoofDPI recognizes when request wants it to proxy connection SpoofDPI proxy itself.

## Actual behavior

Infinite recursion, see below

# How To Reproduce?

1. Run `spoof-dpi --debug`
2. `curl -v http://127.0.0.1`
3. Observe endless stream of 

```
...
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Start                                 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Finished 127.0.0.1:48844              
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Closing client Connection.. 127.0.0.1:48844 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] New connection to the server 127.0.0.1 127.0.0.1:50862 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Error reading from 127.0.0.1:48844 timed out 
DEBU[2024-07-21T19:54:17+03:00] [PROXY] Request from 127.0.0.1:50862

GET / HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/8.8.0
Accept: */*
 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Start                                 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Closing server Connection.. 127.0.0.1 127.0.0.1:48858 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Sent a request to 127.0.0.1           
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Finished 127.0.0.1:48858              
DEBU[2024-07-21T19:54:17+03:00] [HTTP] New connection to the server 127.0.0.1 127.0.0.1:50876 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Closing client Connection.. 127.0.0.1:48858 
DEBU[2024-07-21T19:54:17+03:00] [HTTP] Sent a request to 127.0.0.1           
DEBU[2024-07-21T19:54:17+03:00] [PROXY] Request from 127.0.0.1:50876
...
```

# Client information

**OS**: Arch linux 

**Version**: latest git at the moment: 83326a0a663a0cad0ab62bbbb8863b09f937718e

# How it could be fixed

Pass which port proxy is listening on to HandleHttp(s) methods, then right after this

https://github.com/xvzc/SpoofDPI/blob/83326a0a663a0cad0ab62bbbb8863b09f937718e/net/conn.go#L73-L76

Add (after the types are properly converted)

```go
	// Avoid recursively querying self
	if port == proxyPort && isOurAddress(net.ParseIP(ip)) {
		log.Error("[HTTP] Invalid request: final target has the same IP and port as our proxy")
		lConn.Close()
		return
	}
```

Where `isOurAddress()` is 

```go
// Check if a given IPv4 assigned to one of our host's network interfaces
// Doesn't handle WAN addresses
// WARNING: needs access to AF_NETLINK address family to work on Linux. 
// This is usually not a problem, unless you're filtering system calls or
// running it as systemd service with RestrictAddressFamilies. 
func isOurAddress(ip net.IP) bool {
	// we don't handle IPv6 at all it seems
	if ip.To4() == nil {
		return false
	}

	if ip.IsLoopback() {
		return true
	}

	// Get list of available addresses
	// See `ip -4 addr show`
	addr, err := net.InterfaceAddrs() // needs AF_NETLINK on linux
	if err != nil {
		log.Error("[IP CHECK] Error while getting addresses of our network interfaces: ", err)
		return false
	}

	for _, addr := range addr {
		if ipnet, ok := addr.(*net.IPNet); ok {
			if ipnet.IP.To4() != nil && ipnet.IP.To4().Equal(ip) {
				return true
			}
		}
	}
	return false
}

```

so basically:

<details><summary>Patch</summary>
<p>

```patch
diff --git a/net/conn.go b/net/conn.go
index e152854..e7c202c 100644
--- a/net/conn.go
+++ b/net/conn.go
@@ -59,7 +59,37 @@ func (conn *Conn) ReadBytes() ([]byte, error) {
 	return ret, nil
 }
 
-func (lConn *Conn) HandleHttp(p *packet.HttpPacket, timeout int, resolver *dns.DnsResolver) {
+// Check if a given IPv4 assigned to one of our host's network interfaces
+// Doesn't handle WAN addresses
+func isOurAddress(ip net.IP) bool {
+	// we don't handle IPv6 at all it seems
+	if ip.To4() == nil {
+		return false
+	}
+
+	if ip.IsLoopback() {
+		return true
+	}
+
+	// Get list of available addresses
+	// See `ip -4 addr show`
+	addr, err := net.InterfaceAddrs()
+	if err != nil {
+		log.Error("[IP CHECK] Error while getting addresses of our network interfaces: ", err)
+		return false
+	}
+
+	for _, addr := range addr {
+		if ipnet, ok := addr.(*net.IPNet); ok {
+			if ipnet.IP.To4() != nil && ipnet.IP.To4().Equal(ip) {
+				return true
+			}
+		}
+	}
+	return false
+}
+
+func (lConn *Conn) HandleHttp(p *packet.HttpPacket, timeout int, resolver *dns.DnsResolver, proxyPort string) {
 	p.Tidy()
 
 	ip, err := resolver.Lookup(p.Domain())
@@ -75,6 +105,13 @@ func (lConn *Conn) HandleHttp(p *packet.HttpPacket, timeout int, resolver *dns.D
 		port = p.Port()
 	}
 
+	// Avoid recursively querying self
+	if port == proxyPort && isOurAddress(net.ParseIP(ip)) {
+		log.Error("[HTTP] Invalid request: final target has the same IP and port as our proxy")
+		lConn.Close()
+		return
+	}
+
 	rConn, err := DialTCP("tcp", ip, port)
 	if err != nil {
 		log.Debug("[HTTP] ", err)
@@ -105,7 +142,7 @@ func (lConn *Conn) HandleHttp(p *packet.HttpPacket, timeout int, resolver *dns.D
 
 }
 
-func (lConn *Conn) HandleHttps(p *packet.HttpPacket, timeout int, resolver *dns.DnsResolver) {
+func (lConn *Conn) HandleHttps(p *packet.HttpPacket, timeout int, resolver *dns.DnsResolver, proxyPort string) {
   ip, err := resolver.Lookup(p.Domain())
 
 	if err != nil {
@@ -120,6 +157,13 @@ func (lConn *Conn) HandleHttps(p *packet.HttpPacket, timeout int, resolver *dns.
 		port = p.Port()
 	}
 
+	// Avoid recursively querying self
+	if port == proxyPort && isOurAddress(net.ParseIP(ip)) {
+		log.Error("[HTTPS] Invalid request: final target has the same IP and port as our proxy")
+		lConn.Close()
+		return
+	}
+
 	rConn, err := DialTCP("tcp4", ip, port)
 	if err != nil {
 		log.Debug("[HTTPS] ", err)
diff --git a/proxy/proxy.go b/proxy/proxy.go
index 7831f41..dab6620 100644
--- a/proxy/proxy.go
+++ b/proxy/proxy.go
@@ -3,6 +3,7 @@ package proxy
 import (
 	"fmt"
 	"os"
+	"strconv"
 
 	log "github.com/sirupsen/logrus"
 	"github.com/xvzc/SpoofDPI/dns"
@@ -72,12 +73,13 @@ func (p *Proxy) Start() {
 				return
 			}
 
+			proxyPort := strconv.Itoa(p.Port())
 			if pkt.IsConnectMethod() {
 				log.Debug("[HTTPS] Start")
-				conn.HandleHttps(pkt, p.timeout, p.resolver)
+				conn.HandleHttps(pkt, p.timeout, p.resolver, proxyPort)
 			} else {
 				log.Debug("[HTTP] Start")
-				conn.HandleHttp(pkt, p.timeout, p.resolver)
+				conn.HandleHttp(pkt, p.timeout, p.resolver, proxyPort)
 			}
 		}()
 	}

```

</p>
</details> 

which results the above request being handled like so:

```
...
DEBU[2024-07-21T20:18:01+03:00] [PROXY] Request from 127.0.0.1:51484

GET / HTTP/1.1
Host: 127.0.0.1:8080
User-Agent: curl/8.8.0
Accept: */*
 
DEBU[2024-07-21T20:18:01+03:00] [HTTP] Start                                 
ERRO[2024-07-21T20:18:01+03:00] [HTTP] Invalid request: final target has the same IP and port as our proxy 
*continuing as normal*
```

# Another note

Also, while hunting down why it did so, I noticed that you don't close connections on errors.

E.g. connections here
https://github.com/xvzc/SpoofDPI/blob/83326a0a663a0cad0ab62bbbb8863b09f937718e/proxy/proxy.go#L66
https://github.com/xvzc/SpoofDPI/blob/83326a0a663a0cad0ab62bbbb8863b09f937718e/proxy/proxy.go#L71

and here (same with HandleHttps)
https://github.com/xvzc/SpoofDPI/blob/83326a0a663a0cad0ab62bbbb8863b09f937718e/net/conn.go#L66-L69
https://github.com/xvzc/SpoofDPI/blob/83326a0a663a0cad0ab62bbbb8863b09f937718e/net/conn.go#L79-L81

should be closed manually because the `defer` doesn't handle them as it is defined later (thus we return **before** it's defined), otherwise the client which made the request will hang until its timeout. But as far as I can tell it doesn't result in anything truly problematic.

**Comment by xvzc** [comment]
Can not reproduce. Could you give me an exact case that occuring this issue?
1. command to run spoof-dpi
2. the website that raises this issue

**Comment by MahouShoujoMivutilde** [comment]
The site is not important, because there is no site, because it happens when you try to http GET the proxy address _itself_ (hence why _invalid_ request). 

I gave it in description above:
1. Run `spoof-dpi --debug`
2. `curl -v http://127.0.0.1`

I get that it's not a valid request to make in a first place (valid would be `curl --proxy http://127.0.0.1 example.com`), but I think spoof-dpi should reject it and not serve it, as opposed to this:

https://github.com/user-attachments/assets/0a7eb9ce-54e9-489f-87f0-28cd3c6be425

Same thing will happen if you just open `http://127.0.0.1:8080` in your browser. Of course, none of this is normal usage, but I think it shouldn't hammer the cpu for no reason and just reject such request.

Maybe it doesn't happen on Mac for some reason?

**Comment by xvzc** [comment]
Yeah this makes sense. Thank you for reporting issue. I will fix this as soon as possible.

**Comment by xvzc** [comment]
Resolved.

**Comment by MahouShoujoMivutilde** [comment]
Thank you!

Also, I think it'll be good to note that, in README, this:

> What SpoofDPI does to bypass this is to send the first 1 byte of a request to the server, **and then send the rest**

Is no longer true, and now `client hello` is fragmented in chunks of equal size, size of which is determined by new `--window-size` argument, and that users should experiment with its value, if default does not work for them. 

For example, new 50 bytes chunks default doesn't bypass my ISP's DPI while old simpler split in 2 chunk, first 1 byte and the rest, works fine. The _maximum_ size which still bypasses mine is as low as `--window-size 2`. Of course, that depends on DPI, maybe 50 works fine for someone.

What I propose is something like this in `--help` (and readme):

```
...
  -window-size int
    	chunk size, in number of bytes, for fragmented client hello,
        try lower values if default doesn't bypass the DPI (default 50)
...
```

**Comment by xvzc** [comment]
Currerntly in progress
