### ISSUE TITLE
Installation via Homebrew

### ISSUE THREAD

**Issue by rakleed** [xvzc/SpoofDPI#68]
Can you please add the ability to install via Homebrew?

https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by xvzc** [comment]
For macos?

**Comment by 10wpressure** [comment]
This way it's one command "brew upgrade" to upgrade all the applications.

**Comment by pavelkogen** [comment]
Up

**Comment by Ledorub** [comment]
Merged #204.
