### ISSUE TITLE
Release v0.8 latest working for Youtube on MacOS Sonoma 14.5

### ISSUE THREAD

**Issue by denmorgenshtern** [xvzc/SpoofDPI#73]
I have checked all builds since the latest v0.10.2. They start, but YouTube does not work. Not a single video starts at all. Everything worked fine on v0.8 in 4K.

**Comment by xvzc** [comment]
The difference is that dns over https and legacy style fragmentation of client hello packet are disabled by default.
Try adding --enable-doh and --window-size 0 options and let me know how it goes

**Comment by noviligx** [comment]
@xvzc it works!!!

**Comment by denmorgenshtern** [comment]
I tried all 3 options variants, equally bad.:
spoof-dpi --enable-dog --window-size 0
spoof-dpi --enable-dog
spoof-dpi --window-size 0
At least the video starts at 144p, but it doesn't work even in 1080p.

**Comment by xvzc** [comment]
@denmorgenshtern Maybe try setting the timeout value to a bigger value? like `--timeout 10000`
