### ISSUE TITLE
Can't connect to the proxy from termux

### ISSUE THREAD

**Issue by WtFNickNameLoL** [xvzc/SpoofDPI#74]
# Describe the bug
I can't connect to the proxy from termux I'm used arm64 bin and it's starting but I can't connect to it
V proxid gives error

**OS**:
Android 14
**Version**:
Latest 
# Additional context
Sorry for disturbing

**Comment by xvzc** [comment]
This application is not throughly tested on Android OS Sorry..

**Comment by WtFNickNameLoL** [comment]
Sadly
