### ISSUE TITLE
Need help with make tweak for iOS for using SpoofDPI

### ISSUE THREAD

**Issue by Leeksov** [xvzc/SpoofDPI#77]
# Overview
SpoofDPI for iOS (jailbreak/jailed)
# Description
Help in writing a tweak for iOS that allows you to use this utility for the entire system using Jailbreak/Proxy App or by adding the tweak to the .ipa file of a specific desired application
# Due date
soon?
# Additional context

**Comment by xvzc** [comment]
Sorry that i can't get you any help cuz i have no experience or knowledge in iOS, and spoof-dpi is basically built for linux and macos.

**Comment by Leeksov** [comment]
> Sorry that i can't get you any help cuz i have no experience or knowledge in iOS, and spoof-dpi is basically built for linux and macos.

Can you help with make binary for iOS? Idk how use gomobile
