### ISSUE TITLE
Support for Mac with arm64 chips

### ISSUE THREAD

**Issue by Moreez317** [xvzc/SpoofDPI#78]
Hi! I just download sources and build latest version for darwin/arm64 on my Mac, and it works good. 

Can you add arm64 version for MacOS in next release please?

Thank you for this app, really helps a lot!

**Comment by xvzc** [comment]
Did you try with darwin/amd64 version?

**Comment by zheludkd** [comment]
> Did you try with darwin/amd64 version?

Hey, thank you. that works on M1

**Comment by zoto-ff** [comment]
darwin/amd64 "just works" thanks to Rosetta. but you can manually build arm64 binary from source

**Comment by Moreez317** [comment]
Oh, I'm sorry, i new with arm Mac's, and forgot about Rosetta, everything works. Thanks!
