### ISSUE TITLE
Could not turn on it after disabling and after disabling apps doesn't have internet 

### ISSUE THREAD

**Issue by hookjabber** [xvzc/SpoofDPI#79]
If I switch this thing off, it won't switch back on unless I restart the computer. Mac os 14.0 m2
Error message: [PROXY] Error creating listener: listen tcp4 127.0.0.1:8080: bind: address already in use

**Comment by hookjabber** [comment]
Also, as soon as I switch it off, the internet stops working in other applications (safari, firefox, discord), it works only in chrome rebooting does not help. how do I get everything back again?

**Comment by debug45** [comment]
Have you managed to solve the problem? How did you do it?

**Comment by hookjabber** [comment]
> Have you managed to solve the problem? How did you do it?

Manually by finding spoof-dpi process that uses port 8080(sudo lsof -i :8080), after that just kill it(sudo kill "PID")
After that if you don't want to use this anymore you can simply delete spoof-dpi folder
