### ISSUE TITLE
Looks at all URLs, not just those specified at startup

### ISSUE THREAD

**Issue by augustvavreliy** [xvzc/SpoofDPI#80]
# Describe the bug

Looks at all URLs, not just those specified at startup

## Expected behavior

look  just those specified at startup

## Actual behavior

Looks at all URLs, not just those specified at startup

# How To Reproduce?
 launch with this options: spoof-dpi  -url youtube.com -url googlevideo.com  -window-size 0 -debug

# Client information

**OS**: macOS 

**Version**: 14.6 

# Additional context
![image](https://github.com/user-attachments/assets/e1fefe11-f4a5-4526-a41a-0cb998316634)

**Comment by xvzc** [comment]
As spoof-dpi sets the proxy config of your OS on start up, this is an expected behavior. it performs TCP Level fragmentation of client hello for the given urls and just bypass all other packets as it does't exist for the rest.

**Comment by augustvavreliy** [comment]
So, why chat on Twitch.tv cant connect when spoofdpi active?
![image](https://github.com/user-attachments/assets/b8e53a1c-df2c-4fde-9b31-1af6200efc00)
![image](https://github.com/user-attachments/assets/a05ac62a-9269-4424-b6e6-409df72e6fe8)

https://github.com/user-attachments/assets/c7790e6c-9c42-43b2-81de-d8a828b3f163

**Comment by xvzc** [comment]
spoof-dpi version?

**Comment by augustvavreliy** [comment]
spoog-dpi v0.10.2

**Comment by xvzc** [comment]
Try the latest version

**Comment by augustvavreliy** [comment]
It seems to work, thanks
