### ISSUE TITLE
Error reading from 1----0:443 timed out

### ISSUE THREAD

**Issue by tim1737** [xvzc/SpoofDPI#81]
mac os arm Error reading from 8-------0:443 timed out 
please tell when the update is planned

**Comment by xvzc** [comment]
could you attach a screenshot?

**Comment by tim1737** [comment]
![Uploading Screenshot 2024-08-03 at 08.47.19.png…]()

**Comment by tim1737** [comment]
<img width="1512" alt="1" src="https://github.com/user-attachments/assets/517e04e6-ba33-4d8b-92aa-1f55f2f6c1b3">

**Comment by tim1737** [comment]
rus
