### ISSUE TITLE
please tell me how you can delete all binaries

### ISSUE THREAD

**Issue by tim1737** [xvzc/SpoofDPI#82]
please tell me how you can delete all binaries

**Comment by xvzc** [comment]
nothing special. just remove ~/.spoof-dpi directory

**Comment by Rassska** [comment]
@xvzc, after doing so, internet is unavailable. Any logs i can provide? I regret not doing it on vm or somewhere.

**Comment by xvzc** [comment]
MacOs?

**Comment by xvzc** [comment]
Go to your wifi settings and turn off the proxy
