### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by tim1737** [xvzc/SpoofDPI#83]
Error reading from 127.0.0.1:58996 timed out 
Error reading from 149.153.167.35:443 timed out
pls help

**Comment by tim1737** [comment]
region rus

**Comment by xvzc** [comment]
timeouts are expected behavior if it does not occur any unstable connection on your browser.

**Comment by tim1737** [comment]
the connection is stable, but YouTube does not work completely with the software turned on

**Comment by xvzc** [comment]
connections will be timed out if there is no packet received or sent for 2000ms by default. In that case it closes the socket and reopens when needed. This is an expected behavior that has been programmed to save the number of ports

**Comment by tim1737** [comment]
![324](https://github.com/user-attachments/assets/7106daf3-186b-44d1-b06e-7a080a321b5c)

**Comment by xvzc** [comment]
Would you try give the bigger timeout value? maybe 
--timeout 5000

**Comment by Serega007RU** [comment]
this has a bad effect on discord, it tries to reconnect every 2-3 seconds
![image](https://github.com/user-attachments/assets/e2aabb51-5026-482f-818c-2cbf52f4f9d1)

**Comment by tim1737** [comment]
Okay, I'll try, but I don't think it's going to help.
![1423](https://github.com/user-attachments/assets/a052caea-08a1-4ba1-a05b-6aca71ff5f5f)

**Comment by tim1737** [comment]
increased to 10,000 as well

**Comment by xvzc** [comment]
@Serega007RU reproduced on discord i will fix it and upload the release now

**Comment by tim1737** [comment]
@xvzc 
please tell me what can be done in my case

**Comment by xvzc** [comment]
@tim1737 @Serega007RU Please try v0.10.3

**Comment by tim1737** [comment]
DEBU[2024-08-03T09:37:00+03:00] [PROXY] Request from 127.0.0.1:62416

CONNECT play.google.com:443 HTTP/1.1
Host: play.google.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 
DEBU[2024-08-03T09:37:00+03:00] [PROXY] Request from 127.0.0.1:62417

CONNECT play.google.com:443 HTTP/1.1
Host: play.google.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] New connection to the server api.vk.com 192.168.1.2:62415 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Sent 200 Connection Estabalished to 127.0.0.1:62414 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Client sent hello 2055bytes          
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Writing chunked client hello to api.vk.com 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Chunking client hello.               
DEBU[2024-08-03T09:37:00+03:00] [DNS] resolved play.google.com: 64.233.161.113 
DEBU[2024-08-03T09:37:00+03:00] [PROXY] Start HTTPS                          
DEBU[2024-08-03T09:37:00+03:00] [DNS] resolved play.google.com: 173.194.221.138 
DEBU[2024-08-03T09:37:00+03:00] [PROXY] Start HTTPS                          
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] New connection to the server play.google.com 192.168.1.2:62418 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Sent 200 Connection Estabalished to 127.0.0.1:62416 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Client sent hello 1821bytes          
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Writing chunked client hello to play.google.com 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Chunking client hello.               
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] New connection to the server play.google.com 192.168.1.2:62419 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Sent 200 Connection Estabalished to 127.0.0.1:62417 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Client sent hello 1789bytes          
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Writing chunked client hello to play.google.com 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Chunking client hello.               
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Error reading from 64.233.161.113:443 timed out 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Error reading from 173.194.221.138:443 timed out 
DEBU[2024-08-03T09:37:00+03:00] [PROXY] Request from 127.0.0.1:62420

CONNECT im.vk.com:443 HTTP/1.1
Host: im.vk.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 
DEBU[2024-08-03T09:37:00+03:00] [DNS] resolved im.vk.com: 93.186.225.201     
DEBU[2024-08-03T09:37:00+03:00] [PROXY] Start HTTPS                          
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] New connection to the server im.vk.com 192.168.1.2:62421 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Sent 200 Connection Estabalished to 127.0.0.1:62420 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Client sent hello 2022bytes          
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Writing chunked client hello to im.vk.com 
DEBU[2024-08-03T09:37:00+03:00] [HTTPS] Chunking client hello.               
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Error reading from 127.0.0.1:62364 timed out 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Closing client Connection.. 127.0.0.1:62364 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Closing server Connection.. queuev4.vk.com 192.168.1.2:62367 
DEBU[2024-08-03T09:37:01+03:00] [PROXY] Request from 127.0.0.1:62422

CONNECT queuev4.vk.com:443 HTTP/1.1
Host: queuev4.vk.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 
DEBU[2024-08-03T09:37:01+03:00] [DNS] resolved queuev4.vk.com: 93.186.225.201 
DEBU[2024-08-03T09:37:01+03:00] [PROXY] Start HTTPS                          
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] New connection to the server queuev4.vk.com 192.168.1.2:62423 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Sent 200 Connection Estabalished to 127.0.0.1:62422 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Client sent hello 2091bytes          
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Writing chunked client hello to queuev4.vk.com 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Chunking client hello.               
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Error reading from 127.0.0.1:62392 timed out 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Closing client Connection.. 127.0.0.1:62392 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Closing server Connection.. www.youtube.com 192.168.1.2:62393 
DEBU[2024-08-03T09:37:01+03:00] [PROXY] Request from 127.0.0.1:62424

CONNECT www.youtube.com:443 HTTP/1.1
Host: www.youtube.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
 
DEBU[2024-08-03T09:37:01+03:00] [DNS] resolved www.youtube.com: 209.85.233.198 
DEBU[2024-08-03T09:37:01+03:00] [PROXY] Start HTTPS                          
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] New connection to the server www.youtube.com 192.168.1.2:62425 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Sent 200 Connection Estabalished to 127.0.0.1:62424 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Client sent hello 1821bytes          
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Writing chunked client hello to www.youtube.com 
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Chunking client hello.               
DEBU[2024-08-03T09:37:01+03:00] [HTTPS] Error reading from 209.85.233.198:443 timed out 
DEBU[2024-08-03T09:37:02+03:00] [HTTPS] Error reading from 127.0.0.1:62394 timed out 
DEBU[2024-08-03T09:37:02+03:00] [HTTPS] Closing client Connection.. 127.0.0.1:62394 
DEBU[2024-08-03T09:37:02+03:00] [HTTPS] Error reading from 13.248.151.210:443 timed out 
DEBU[2024-08-03T09:37:02+03:00] [HTTPS] Closing server Connection.. clientstream.launchdarkly.com 192.168.1.2:62395 
DEBU[2024-08-03T09:37:04+03:00] [PROXY] Request from 127.0.0.1:62426

**Comment by xvzc** [comment]
What is your run command ?

**Comment by tim1737** [comment]
ims-MacBook-Pro:~ tim.$ curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11565    0 11565    0     0  38998      0 --:--:-- --:--:-- --:--:-- 39070
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2808k  100 2808k    0     0  2439k      0  0:00:01  0:00:01 --:--:-- 2439k
x ./spoof-dpi

Successfully installed SpoofDPI.
Please add the line below to your rcfile(.bashrc or .zshrc etc..)

>>    export PATH=$PATH:~/.spoof-dpi/bin
Tims-MacBook-Pro:~ tim.$ export PATH=$PATH:~/.spoof-dpi/bin
Tims-MacBook-Pro:~ tim.$ cd .spoof-dpi/
Tims-MacBook-Pro:.spoof-dpi tim.$ ls
bin
Tims-MacBook-Pro:.spoof-dpi tim.$ cd bin/
Tims-MacBook-Pro:bin tim.$ ls
spoof-dpi
Tims-MacBook-Pro:bin tim.$ clear



























Tims-MacBook-Pro:bin tim.$ spoof-dpi -debug -timeout 10000
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██ 
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██ 
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██ 
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██ 
███████ ██       ██████   ██████  ██      ██████  ██      ██ 

• ADDR    : 127.0.0.1
• PORT    : 8080
• DNS     : 8.8.8.8
• DEBUG   : true

INFO[2024-08-03T09:36:06+03:00] [PROXY] Connection timeout is set to 10000ms 
INFO[2024-08-03T09:36:06+03:00] [PROXY] Created a listener on port 8080      
DEBU[2024-08-03T09:36:07+03:00] [PROXY] Request from 127.0.0.1:62270

**Comment by xvzc** [comment]
you can now disable the --timeout option. would you try giving `--window-size 0`?

**Comment by tim1737** [comment]
Tims-MacBook-Pro:bin tim.$ spoof-dpi -debug --window-size 0
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██ 
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██ 
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██ 
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██ 
███████ ██       ██████   ██████  ██      ██████  ██      ██ 

• ADDR    : 127.0.0.1
• PORT    : 8080
• DNS     : 8.8.8.8
• DEBUG   : true

FATA[2024-08-03T09:45:24+03:00] exit status 4                                
Tims-MacBook-Pro:bin tim.$ spoof-dpi -debug -window-size 0
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██ 
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██ 
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██ 
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██ 
███████ ██       ██████   ██████  ██      ██████  ██      ██ 

• ADDR    : 127.0.0.1
• PORT    : 8080
• DNS     : 8.8.8.8
• DEBUG   : true

FATA[2024-08-03T09:45:33+03:00] exit status 4                                
Tims-MacBook-Pro:bin tim.$ spoof-dpi --window-size 0
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██ 
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██ 
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██ 
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██ 
███████ ██       ██████   ██████  ██      ██████  ██      ██ 

• ADDR    : 127.0.0.1
• PORT    : 8080
• DNS     : 8.8.8.8
• DEBUG   : false

FATA[2024-08-03T09:46:24+03:00] exit status 4                                
Tims-MacBook-Pro:bin tim.$ spoof-dpi --window-size 1
███████ ██████   ██████   ██████  ███████ ██████  ██████  ██ 
██      ██   ██ ██    ██ ██    ██ ██      ██   ██ ██   ██ ██ 
███████ ██████  ██    ██ ██    ██ █████   ██   ██ ██████  ██ 
     ██ ██      ██    ██ ██    ██ ██      ██   ██ ██      ██ 
███████ ██       ██████   ██████  ██      ██████  ██      ██ 

• ADDR    : 127.0.0.1
• PORT    : 8080
• DNS     : 8.8.8.8
• DEBUG   : false

FATA[2024-08-03T09:46:28+03:00] exit status 4                                
Tims-MacBook-Pro:bin tim.$ spoof-dpi --window-size

**Comment by xvzc** [comment]
reboot your system

**Comment by tim1737** [comment]
thank you very very much

**Comment by xvzc** [comment]
issue solved?
