### ISSUE TITLE
Looped request has been detected

### ISSUE THREAD

**Issue by Freemorger** [xvzc/SpoofDPI#95]
# Describe the bug
When I'm using it, im getting error in terminal:
`ERRO[] [PROXY] Looped request has been detected. aborting. `

## Expected behavior
Bypass dpi

## Actual behavior
Not bypassing dpi

# How To Reproduce?
Run `spoof-dpi`
Specify http://127.0.0.1:8080 as prozy in system settings
try to go at any website with restrictions

# Client information

**OS**: Endeavour OS (linux)

**Version**: linux 6.10.2

# Additional context

**Comment by xvzc** [comment]
The error happens when you try to send a http request to 127.0.0.1:8080 which shouldn't be sent because that will occur an looped request
