### ISSUE TITLE
Binary for darwin-arm64 is missing

### ISSUE THREAD

**Issue by antony66** [xvzc/SpoofDPI#96]
Hey guys!

Looks like the binary for darwin-arm64 platform is missing. The installation command you provided is:

    curl -fsSL https://raw.githubusercontent.com/xvzc/SpoofDPI/main/install.sh | bash -s darwin-arm64

and it simply gives:

```
tar: Error opening archive: Unrecognized archive format
Error. exiting now
```

because the downloaded tar is actually not an archive, it's a text file that contains string "Not Found"

**Comment by ggoofie** [comment]
> Will be added in next release. you can still run amd64's binary it works.
Run amd64's binary on Apple Silicon, but... 
```console
╰─ spoof-dpi
zsh: exec format error: spoof-dpi
``` 

Waiting fix tar.gz for Apple Silicon) Thanks

**Comment by vgglv** [comment]
when you build from sources it will generate valid arm64 binary
